// Package simulationengine provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package simulationengine

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for BatchDataStatus.
const (
	Completed BatchDataStatus = "completed"
	Failed    BatchDataStatus = "failed"
	Partial   BatchDataStatus = "partial"
)

// Defines values for GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetParamsDistributionType.
const (
	All       GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetParamsDistributionType = "all"
	AwayScore GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetParamsDistributionType = "away_score"
	HomeScore GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetParamsDistributionType = "home_score"
	Margin    GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetParamsDistributionType = "margin"
	Total     GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetParamsDistributionType = "total"
)

// BatchData defines model for BatchData.
type BatchData struct {
	BatchId         string            `json:"batch_id"`
	CompletedAt     string            `json:"completed_at"`
	CompletedGames  int               `json:"completed_games"`
	FailedGames     int               `json:"failed_games"`
	Results         []BatchGameResult `json:"results"`
	StartedAt       string            `json:"started_at"`
	Status          BatchDataStatus   `json:"status"`
	TotalDurationMs int               `json:"total_duration_ms"`
	TotalGames      int               `json:"total_games"`
}

// BatchDataStatus defines model for BatchData.Status.
type BatchDataStatus string

// BatchGameRequest defines model for BatchGameRequest.
type BatchGameRequest struct {
	Config *SimulationConfigIn `json:"config"`
	GameId string              `json:"game_id"`
}

// BatchGameResult defines model for BatchGameResult.
type BatchGameResult struct {
	Cached          *bool               `json:"cached,omitempty"`
	Error           *string             `json:"error"`
	GameId          string              `json:"game_id"`
	Result          *BatchResultSummary `json:"result"`
	SimulationRunId *string             `json:"simulation_run_id"`
	Status          string              `json:"status"`
}

// BatchRequest defines model for BatchRequest.
type BatchRequest struct {
	DefaultConfig *SimulationConfigIn `json:"default_config,omitempty"`
	ForceRefresh  *bool               `json:"force_refresh,omitempty"`
	Games         []BatchGameRequest  `json:"games"`
}

// BatchResultSummary defines model for BatchResultSummary.
type BatchResultSummary struct {
	AwayWinProbability float32 `json:"away_win_probability"`
	HomeWinProbability float32 `json:"home_win_probability"`
	MeanMargin         float32 `json:"mean_margin"`
	MeanTotal          float32 `json:"mean_total"`
}

// Distribution defines model for Distribution.
type Distribution struct {
	Max    int                `json:"max"`
	Mean   float32            `json:"mean"`
	Min    int                `json:"min"`
	StdDev float32            `json:"std_dev"`
	Type   *string            `json:"type,omitempty"`
	Values map[string]float32 `json:"values"`
}

// DistributionsData defines model for DistributionsData.
type DistributionsData struct {
	Distributions       map[string]Distribution `json:"distributions"`
	GameId              string                  `json:"game_id"`
	IterationsCompleted int                     `json:"iterations_completed"`
	SimulationRunId     string                  `json:"simulation_run_id"`
}

// EnvelopeBatchData defines model for Envelope_BatchData_.
type EnvelopeBatchData struct {
	Data BatchData `json:"data"`
	Meta Meta      `json:"meta"`
}

// EnvelopeDistributionsData defines model for Envelope_DistributionsData_.
type EnvelopeDistributionsData struct {
	Data DistributionsData `json:"data"`
	Meta Meta              `json:"meta"`
}

// EnvelopeHealthData defines model for Envelope_HealthData_.
type EnvelopeHealthData struct {
	Data HealthData `json:"data"`
	Meta Meta       `json:"meta"`
}

// EnvelopeSimulationRunData defines model for Envelope_SimulationRunData_.
type EnvelopeSimulationRunData struct {
	Data SimulationRunData `json:"data"`
	Meta Meta              `json:"meta"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// HealthData defines model for HealthData.
type HealthData struct {
	Dependencies  map[string]string `json:"dependencies"`
	Load          HealthLoad        `json:"load"`
	Service       *string           `json:"service,omitempty"`
	Status        string            `json:"status"`
	UptimeSeconds int               `json:"uptime_seconds"`
	Version       string            `json:"version"`
}

// HealthLoad defines model for HealthLoad.
type HealthLoad struct {
	ActiveSimulations int `json:"active_simulations"`
	AvgDurationMs     int `json:"avg_duration_ms"`
	MaxConcurrent     int `json:"max_concurrent"`
	QueuedSimulations int `json:"queued_simulations"`
	SimulationsToday  int `json:"simulations_today"`
}

// Meta defines model for Meta.
type Meta struct {
	RequestId string    `json:"request_id"`
	Timestamp time.Time `json:"timestamp"`
}

// Percentiles defines model for Percentiles.
type Percentiles struct {
	Margin map[string]int `json:"margin"`
	Total  map[string]int `json:"total"`
}

// SimulationConfigIn defines model for SimulationConfigIn.
type SimulationConfigIn struct {
	ConvergenceThreshold *float32                `json:"convergence_threshold,omitempty"`
	Iterations           *int                    `json:"iterations,omitempty"`
	PluginConfig         *map[string]interface{} `json:"plugin_config,omitempty"`
	RandomSeed           *int                    `json:"random_seed"`
}

// SimulationConfigOut defines model for SimulationConfigOut.
type SimulationConfigOut struct {
	ConvergenceThreshold float32 `json:"convergence_threshold"`
	Iterations           int     `json:"iterations"`
	RandomSeed           *int    `json:"random_seed"`
	Sport                string  `json:"sport"`
}

// SimulationRequest defines model for SimulationRequest.
type SimulationRequest struct {
	Config       *SimulationConfigIn `json:"config,omitempty"`
	ForceRefresh *bool               `json:"force_refresh,omitempty"`
	GameId       string              `json:"game_id"`
}

// SimulationResultData defines model for SimulationResultData.
type SimulationResultData struct {
	AwayWinProbability       float32            `json:"away_win_probability"`
	DrawProbability          float32            `json:"draw_probability"`
	HomeWinProbability       float32            `json:"home_win_probability"`
	Id                       string             `json:"id"`
	MeanAwayScore            float32            `json:"mean_away_score"`
	MeanHomeScore            float32            `json:"mean_home_score"`
	MeanMargin               float32            `json:"mean_margin"`
	MeanTotal                float32            `json:"mean_total"`
	Percentiles              Percentiles        `json:"percentiles"`
	SpreadCoverProbabilities map[string]float32 `json:"spread_cover_probabilities"`
	TotalOverProbabilities   map[string]float32 `json:"total_over_probabilities"`
}

// SimulationRunData defines model for SimulationRunData.
type SimulationRunData struct {
	BatchId             *string              `json:"batch_id"`
	Cached              *bool                `json:"cached,omitempty"`
	CompletedAt         string               `json:"completed_at"`
	Config              SimulationConfigOut  `json:"config"`
	Converged           bool                 `json:"converged"`
	DurationMs          int                  `json:"duration_ms"`
	GameId              string               `json:"game_id"`
	IterationsCompleted int                  `json:"iterations_completed"`
	ParametersHash      string               `json:"parameters_hash"`
	Result              SimulationResultData `json:"result"`
	SimulationRunId     string               `json:"simulation_run_id"`
	StartedAt           string               `json:"started_at"`
	Status              string               `json:"status"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input *interface{}               `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// GetLatestSimulationApiV1SimGamesGameIdLatestGetParams defines parameters for GetLatestSimulationApiV1SimGamesGameIdLatestGet.
type GetLatestSimulationApiV1SimGamesGameIdLatestGetParams struct {
	// ForceRefresh If true, trigger a fresh default-config simulation instead of returning cached.
	ForceRefresh *bool `form:"force_refresh,omitempty" json:"force_refresh,omitempty"`

	// ConfigId Reserved for stored simulation configs; accepted and ignored in Phase 2.
	ConfigId *string `form:"config_id,omitempty" json:"config_id,omitempty"`
}

// CreateSimulationApiV1SimSimulationsPostParams defines parameters for CreateSimulationApiV1SimSimulationsPost.
type CreateSimulationApiV1SimSimulationsPostParams struct {
	// XIdempotencyKey UUID for idempotent submission (replayed for 24 hours).
	XIdempotencyKey *string `json:"x-idempotency-key,omitempty"`
}

// GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetParams defines parameters for GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGet.
type GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetParams struct {
	// DistributionType Which distributions to return; 'all' returns every distribution.
	DistributionType *GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetParamsDistributionType `form:"distribution_type,omitempty" json:"distribution_type,omitempty"`
}

// GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetParamsDistributionType defines parameters for GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGet.
type GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetParamsDistributionType string

// CreateSimulationApiV1SimSimulationsPostJSONRequestBody defines body for CreateSimulationApiV1SimSimulationsPost for application/json ContentType.
type CreateSimulationApiV1SimSimulationsPostJSONRequestBody = SimulationRequest

// CreateBatchApiV1SimSimulationsBatchPostJSONRequestBody defines body for CreateBatchApiV1SimSimulationsBatchPost for application/json ContentType.
type CreateBatchApiV1SimSimulationsBatchPostJSONRequestBody = BatchRequest

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetLatestSimulationApiV1SimGamesGameIdLatestGet request
	GetLatestSimulationApiV1SimGamesGameIdLatestGet(ctx context.Context, gameId string, params *GetLatestSimulationApiV1SimGamesGameIdLatestGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealthApiV1SimHealthGet request
	GetHealthApiV1SimHealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateSimulationApiV1SimSimulationsPostWithBody request with any body
	CreateSimulationApiV1SimSimulationsPostWithBody(ctx context.Context, params *CreateSimulationApiV1SimSimulationsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateSimulationApiV1SimSimulationsPost(ctx context.Context, params *CreateSimulationApiV1SimSimulationsPostParams, body CreateSimulationApiV1SimSimulationsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateBatchApiV1SimSimulationsBatchPostWithBody request with any body
	CreateBatchApiV1SimSimulationsBatchPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateBatchApiV1SimSimulationsBatchPost(ctx context.Context, body CreateBatchApiV1SimSimulationsBatchPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSimulationApiV1SimSimulationsSimulationIdGet request
	GetSimulationApiV1SimSimulationsSimulationIdGet(ctx context.Context, simulationId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGet request
	GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGet(ctx context.Context, simulationId string, params *GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetLatestSimulationApiV1SimGamesGameIdLatestGet(ctx context.Context, gameId string, params *GetLatestSimulationApiV1SimGamesGameIdLatestGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLatestSimulationApiV1SimGamesGameIdLatestGetRequest(c.Server, gameId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealthApiV1SimHealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthApiV1SimHealthGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateSimulationApiV1SimSimulationsPostWithBody(ctx context.Context, params *CreateSimulationApiV1SimSimulationsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateSimulationApiV1SimSimulationsPostRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateSimulationApiV1SimSimulationsPost(ctx context.Context, params *CreateSimulationApiV1SimSimulationsPostParams, body CreateSimulationApiV1SimSimulationsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateSimulationApiV1SimSimulationsPostRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateBatchApiV1SimSimulationsBatchPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateBatchApiV1SimSimulationsBatchPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateBatchApiV1SimSimulationsBatchPost(ctx context.Context, body CreateBatchApiV1SimSimulationsBatchPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateBatchApiV1SimSimulationsBatchPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSimulationApiV1SimSimulationsSimulationIdGet(ctx context.Context, simulationId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSimulationApiV1SimSimulationsSimulationIdGetRequest(c.Server, simulationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGet(ctx context.Context, simulationId string, params *GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetRequest(c.Server, simulationId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetLatestSimulationApiV1SimGamesGameIdLatestGetRequest generates requests for GetLatestSimulationApiV1SimGamesGameIdLatestGet
func NewGetLatestSimulationApiV1SimGamesGameIdLatestGetRequest(server string, gameId string, params *GetLatestSimulationApiV1SimGamesGameIdLatestGetParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "game_id", runtime.ParamLocationPath, gameId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/sim/games/%s/latest", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ForceRefresh != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "force_refresh", runtime.ParamLocationQuery, *params.ForceRefresh); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ConfigId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "config_id", runtime.ParamLocationQuery, *params.ConfigId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthApiV1SimHealthGetRequest generates requests for GetHealthApiV1SimHealthGet
func NewGetHealthApiV1SimHealthGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/sim/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateSimulationApiV1SimSimulationsPostRequest calls the generic CreateSimulationApiV1SimSimulationsPost builder with application/json body
func NewCreateSimulationApiV1SimSimulationsPostRequest(server string, params *CreateSimulationApiV1SimSimulationsPostParams, body CreateSimulationApiV1SimSimulationsPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateSimulationApiV1SimSimulationsPostRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateSimulationApiV1SimSimulationsPostRequestWithBody generates requests for CreateSimulationApiV1SimSimulationsPost with any type of body
func NewCreateSimulationApiV1SimSimulationsPostRequestWithBody(server string, params *CreateSimulationApiV1SimSimulationsPostParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/sim/simulations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XIdempotencyKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "x-idempotency-key", runtime.ParamLocationHeader, *params.XIdempotencyKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-idempotency-key", headerParam0)
		}

	}

	return req, nil
}

// NewCreateBatchApiV1SimSimulationsBatchPostRequest calls the generic CreateBatchApiV1SimSimulationsBatchPost builder with application/json body
func NewCreateBatchApiV1SimSimulationsBatchPostRequest(server string, body CreateBatchApiV1SimSimulationsBatchPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateBatchApiV1SimSimulationsBatchPostRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateBatchApiV1SimSimulationsBatchPostRequestWithBody generates requests for CreateBatchApiV1SimSimulationsBatchPost with any type of body
func NewCreateBatchApiV1SimSimulationsBatchPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/sim/simulations/batch")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetSimulationApiV1SimSimulationsSimulationIdGetRequest generates requests for GetSimulationApiV1SimSimulationsSimulationIdGet
func NewGetSimulationApiV1SimSimulationsSimulationIdGetRequest(server string, simulationId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "simulation_id", runtime.ParamLocationPath, simulationId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/sim/simulations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetRequest generates requests for GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGet
func NewGetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetRequest(server string, simulationId string, params *GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "simulation_id", runtime.ParamLocationPath, simulationId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/sim/simulations/%s/distributions", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.DistributionType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "distribution_type", runtime.ParamLocationQuery, *params.DistributionType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetLatestSimulationApiV1SimGamesGameIdLatestGetWithResponse request
	GetLatestSimulationApiV1SimGamesGameIdLatestGetWithResponse(ctx context.Context, gameId string, params *GetLatestSimulationApiV1SimGamesGameIdLatestGetParams, reqEditors ...RequestEditorFn) (*GetLatestSimulationApiV1SimGamesGameIdLatestGetResponse, error)

	// GetHealthApiV1SimHealthGetWithResponse request
	GetHealthApiV1SimHealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthApiV1SimHealthGetResponse, error)

	// CreateSimulationApiV1SimSimulationsPostWithBodyWithResponse request with any body
	CreateSimulationApiV1SimSimulationsPostWithBodyWithResponse(ctx context.Context, params *CreateSimulationApiV1SimSimulationsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateSimulationApiV1SimSimulationsPostResponse, error)

	CreateSimulationApiV1SimSimulationsPostWithResponse(ctx context.Context, params *CreateSimulationApiV1SimSimulationsPostParams, body CreateSimulationApiV1SimSimulationsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateSimulationApiV1SimSimulationsPostResponse, error)

	// CreateBatchApiV1SimSimulationsBatchPostWithBodyWithResponse request with any body
	CreateBatchApiV1SimSimulationsBatchPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateBatchApiV1SimSimulationsBatchPostResponse, error)

	CreateBatchApiV1SimSimulationsBatchPostWithResponse(ctx context.Context, body CreateBatchApiV1SimSimulationsBatchPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateBatchApiV1SimSimulationsBatchPostResponse, error)

	// GetSimulationApiV1SimSimulationsSimulationIdGetWithResponse request
	GetSimulationApiV1SimSimulationsSimulationIdGetWithResponse(ctx context.Context, simulationId string, reqEditors ...RequestEditorFn) (*GetSimulationApiV1SimSimulationsSimulationIdGetResponse, error)

	// GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetWithResponse request
	GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetWithResponse(ctx context.Context, simulationId string, params *GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetParams, reqEditors ...RequestEditorFn) (*GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetResponse, error)
}

type GetLatestSimulationApiV1SimGamesGameIdLatestGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeSimulationRunData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetLatestSimulationApiV1SimGamesGameIdLatestGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetLatestSimulationApiV1SimGamesGameIdLatestGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthApiV1SimHealthGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeHealthData
}

// Status returns HTTPResponse.Status
func (r GetHealthApiV1SimHealthGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthApiV1SimHealthGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateSimulationApiV1SimSimulationsPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *EnvelopeSimulationRunData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r CreateSimulationApiV1SimSimulationsPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateSimulationApiV1SimSimulationsPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateBatchApiV1SimSimulationsBatchPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *EnvelopeBatchData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r CreateBatchApiV1SimSimulationsBatchPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateBatchApiV1SimSimulationsBatchPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSimulationApiV1SimSimulationsSimulationIdGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeSimulationRunData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetSimulationApiV1SimSimulationsSimulationIdGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSimulationApiV1SimSimulationsSimulationIdGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeDistributionsData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetLatestSimulationApiV1SimGamesGameIdLatestGetWithResponse request returning *GetLatestSimulationApiV1SimGamesGameIdLatestGetResponse
func (c *ClientWithResponses) GetLatestSimulationApiV1SimGamesGameIdLatestGetWithResponse(ctx context.Context, gameId string, params *GetLatestSimulationApiV1SimGamesGameIdLatestGetParams, reqEditors ...RequestEditorFn) (*GetLatestSimulationApiV1SimGamesGameIdLatestGetResponse, error) {
	rsp, err := c.GetLatestSimulationApiV1SimGamesGameIdLatestGet(ctx, gameId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetLatestSimulationApiV1SimGamesGameIdLatestGetResponse(rsp)
}

// GetHealthApiV1SimHealthGetWithResponse request returning *GetHealthApiV1SimHealthGetResponse
func (c *ClientWithResponses) GetHealthApiV1SimHealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthApiV1SimHealthGetResponse, error) {
	rsp, err := c.GetHealthApiV1SimHealthGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthApiV1SimHealthGetResponse(rsp)
}

// CreateSimulationApiV1SimSimulationsPostWithBodyWithResponse request with arbitrary body returning *CreateSimulationApiV1SimSimulationsPostResponse
func (c *ClientWithResponses) CreateSimulationApiV1SimSimulationsPostWithBodyWithResponse(ctx context.Context, params *CreateSimulationApiV1SimSimulationsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateSimulationApiV1SimSimulationsPostResponse, error) {
	rsp, err := c.CreateSimulationApiV1SimSimulationsPostWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateSimulationApiV1SimSimulationsPostResponse(rsp)
}

func (c *ClientWithResponses) CreateSimulationApiV1SimSimulationsPostWithResponse(ctx context.Context, params *CreateSimulationApiV1SimSimulationsPostParams, body CreateSimulationApiV1SimSimulationsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateSimulationApiV1SimSimulationsPostResponse, error) {
	rsp, err := c.CreateSimulationApiV1SimSimulationsPost(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateSimulationApiV1SimSimulationsPostResponse(rsp)
}

// CreateBatchApiV1SimSimulationsBatchPostWithBodyWithResponse request with arbitrary body returning *CreateBatchApiV1SimSimulationsBatchPostResponse
func (c *ClientWithResponses) CreateBatchApiV1SimSimulationsBatchPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateBatchApiV1SimSimulationsBatchPostResponse, error) {
	rsp, err := c.CreateBatchApiV1SimSimulationsBatchPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBatchApiV1SimSimulationsBatchPostResponse(rsp)
}

func (c *ClientWithResponses) CreateBatchApiV1SimSimulationsBatchPostWithResponse(ctx context.Context, body CreateBatchApiV1SimSimulationsBatchPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateBatchApiV1SimSimulationsBatchPostResponse, error) {
	rsp, err := c.CreateBatchApiV1SimSimulationsBatchPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBatchApiV1SimSimulationsBatchPostResponse(rsp)
}

// GetSimulationApiV1SimSimulationsSimulationIdGetWithResponse request returning *GetSimulationApiV1SimSimulationsSimulationIdGetResponse
func (c *ClientWithResponses) GetSimulationApiV1SimSimulationsSimulationIdGetWithResponse(ctx context.Context, simulationId string, reqEditors ...RequestEditorFn) (*GetSimulationApiV1SimSimulationsSimulationIdGetResponse, error) {
	rsp, err := c.GetSimulationApiV1SimSimulationsSimulationIdGet(ctx, simulationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSimulationApiV1SimSimulationsSimulationIdGetResponse(rsp)
}

// GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetWithResponse request returning *GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetResponse
func (c *ClientWithResponses) GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetWithResponse(ctx context.Context, simulationId string, params *GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetParams, reqEditors ...RequestEditorFn) (*GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetResponse, error) {
	rsp, err := c.GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGet(ctx, simulationId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetResponse(rsp)
}

// ParseGetLatestSimulationApiV1SimGamesGameIdLatestGetResponse parses an HTTP response from a GetLatestSimulationApiV1SimGamesGameIdLatestGetWithResponse call
func ParseGetLatestSimulationApiV1SimGamesGameIdLatestGetResponse(rsp *http.Response) (*GetLatestSimulationApiV1SimGamesGameIdLatestGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetLatestSimulationApiV1SimGamesGameIdLatestGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeSimulationRunData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetHealthApiV1SimHealthGetResponse parses an HTTP response from a GetHealthApiV1SimHealthGetWithResponse call
func ParseGetHealthApiV1SimHealthGetResponse(rsp *http.Response) (*GetHealthApiV1SimHealthGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthApiV1SimHealthGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeHealthData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateSimulationApiV1SimSimulationsPostResponse parses an HTTP response from a CreateSimulationApiV1SimSimulationsPostWithResponse call
func ParseCreateSimulationApiV1SimSimulationsPostResponse(rsp *http.Response) (*CreateSimulationApiV1SimSimulationsPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateSimulationApiV1SimSimulationsPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest EnvelopeSimulationRunData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseCreateBatchApiV1SimSimulationsBatchPostResponse parses an HTTP response from a CreateBatchApiV1SimSimulationsBatchPostWithResponse call
func ParseCreateBatchApiV1SimSimulationsBatchPostResponse(rsp *http.Response) (*CreateBatchApiV1SimSimulationsBatchPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateBatchApiV1SimSimulationsBatchPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest EnvelopeBatchData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetSimulationApiV1SimSimulationsSimulationIdGetResponse parses an HTTP response from a GetSimulationApiV1SimSimulationsSimulationIdGetWithResponse call
func ParseGetSimulationApiV1SimSimulationsSimulationIdGetResponse(rsp *http.Response) (*GetSimulationApiV1SimSimulationsSimulationIdGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSimulationApiV1SimSimulationsSimulationIdGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeSimulationRunData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetResponse parses an HTTP response from a GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetWithResponse call
func ParseGetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetResponse(rsp *http.Response) (*GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSimulationDistributionsApiV1SimSimulationsSimulationIdDistributionsGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeDistributionsData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
