// Package bookieemulator provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package bookieemulator

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BankrollHistoryDataInterval.
const (
	BankrollHistoryDataIntervalDaily  BankrollHistoryDataInterval = "daily"
	BankrollHistoryDataIntervalPerBet BankrollHistoryDataInterval = "per_bet"
	BankrollHistoryDataIntervalWeekly BankrollHistoryDataInterval = "weekly"
)

// Defines values for BetDataResult.
const (
	BetDataResultLOSS    BetDataResult = "LOSS"
	BetDataResultPENDING BetDataResult = "PENDING"
	BetDataResultPUSH    BetDataResult = "PUSH"
	BetDataResultVOID    BetDataResult = "VOID"
	BetDataResultWIN     BetDataResult = "WIN"
)

// Defines values for BetDetailDataResult.
const (
	BetDetailDataResultLOSS    BetDetailDataResult = "LOSS"
	BetDetailDataResultPENDING BetDetailDataResult = "PENDING"
	BetDetailDataResultPUSH    BetDetailDataResult = "PUSH"
	BetDetailDataResultVOID    BetDetailDataResult = "VOID"
	BetDetailDataResultWIN     BetDetailDataResult = "WIN"
)

// Defines values for BreakdownDataGroupBy.
const (
	BreakdownDataGroupByLeague     BreakdownDataGroupBy = "league"
	BreakdownDataGroupByMarketType BreakdownDataGroupBy = "market_type"
	BreakdownDataGroupByMonth      BreakdownDataGroupBy = "month"
	BreakdownDataGroupBySportsbook BreakdownDataGroupBy = "sportsbook"
)

// Defines values for GradeDataResult.
const (
	GradeDataResultLOSS    GradeDataResult = "LOSS"
	GradeDataResultPENDING GradeDataResult = "PENDING"
	GradeDataResultPUSH    GradeDataResult = "PUSH"
	GradeDataResultVOID    GradeDataResult = "VOID"
	GradeDataResultWIN     GradeDataResult = "WIN"
)

// Defines values for PeriodDataWindow.
const (
	PeriodDataWindowAllTime PeriodDataWindow = "all_time"
	PeriodDataWindowDaily   PeriodDataWindow = "daily"
	PeriodDataWindowMonthly PeriodDataWindow = "monthly"
	PeriodDataWindowWeekly  PeriodDataWindow = "weekly"
)

// Defines values for PlaceBetRequestMarketType.
const (
	PlaceBetRequestMarketTypeMONEYLINE PlaceBetRequestMarketType = "MONEYLINE"
	PlaceBetRequestMarketTypeSPREAD    PlaceBetRequestMarketType = "SPREAD"
	PlaceBetRequestMarketTypeTOTAL     PlaceBetRequestMarketType = "TOTAL"
)

// Defines values for PlaceBetRequestSide.
const (
	AWAY  PlaceBetRequestSide = "AWAY"
	HOME  PlaceBetRequestSide = "HOME"
	OVER  PlaceBetRequestSide = "OVER"
	UNDER PlaceBetRequestSide = "UNDER"
)

// Defines values for GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParamsInterval.
const (
	GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParamsIntervalDaily  GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParamsInterval = "daily"
	GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParamsIntervalPerBet GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParamsInterval = "per_bet"
	GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParamsIntervalWeekly GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParamsInterval = "weekly"
)

// Defines values for ListBetsApiV1EmulatorBetsGetParamsLeague.
const (
	ListBetsApiV1EmulatorBetsGetParamsLeagueMLB     ListBetsApiV1EmulatorBetsGetParamsLeague = "MLB"
	ListBetsApiV1EmulatorBetsGetParamsLeagueNBA     ListBetsApiV1EmulatorBetsGetParamsLeague = "NBA"
	ListBetsApiV1EmulatorBetsGetParamsLeagueNCAABB  ListBetsApiV1EmulatorBetsGetParamsLeague = "NCAA_BB"
	ListBetsApiV1EmulatorBetsGetParamsLeagueNCAABSB ListBetsApiV1EmulatorBetsGetParamsLeague = "NCAA_BSB"
	ListBetsApiV1EmulatorBetsGetParamsLeagueNCAAFB  ListBetsApiV1EmulatorBetsGetParamsLeague = "NCAA_FB"
	ListBetsApiV1EmulatorBetsGetParamsLeagueNFL     ListBetsApiV1EmulatorBetsGetParamsLeague = "NFL"
)

// Defines values for ListBetsApiV1EmulatorBetsGetParamsMarketType.
const (
	ListBetsApiV1EmulatorBetsGetParamsMarketTypeMONEYLINE ListBetsApiV1EmulatorBetsGetParamsMarketType = "MONEYLINE"
	ListBetsApiV1EmulatorBetsGetParamsMarketTypeSPREAD    ListBetsApiV1EmulatorBetsGetParamsMarketType = "SPREAD"
	ListBetsApiV1EmulatorBetsGetParamsMarketTypeTOTAL     ListBetsApiV1EmulatorBetsGetParamsMarketType = "TOTAL"
)

// Defines values for ListBetsApiV1EmulatorBetsGetParamsResult.
const (
	ListBetsApiV1EmulatorBetsGetParamsResultLOSS    ListBetsApiV1EmulatorBetsGetParamsResult = "LOSS"
	ListBetsApiV1EmulatorBetsGetParamsResultPENDING ListBetsApiV1EmulatorBetsGetParamsResult = "PENDING"
	ListBetsApiV1EmulatorBetsGetParamsResultPUSH    ListBetsApiV1EmulatorBetsGetParamsResult = "PUSH"
	ListBetsApiV1EmulatorBetsGetParamsResultVOID    ListBetsApiV1EmulatorBetsGetParamsResult = "VOID"
	ListBetsApiV1EmulatorBetsGetParamsResultWIN     ListBetsApiV1EmulatorBetsGetParamsResult = "WIN"
)

// Defines values for ListBetsApiV1EmulatorBetsGetParamsStatus.
const (
	All    ListBetsApiV1EmulatorBetsGetParamsStatus = "all"
	Graded ListBetsApiV1EmulatorBetsGetParamsStatus = "graded"
	Open   ListBetsApiV1EmulatorBetsGetParamsStatus = "open"
)

// Defines values for GetPerformanceApiV1EmulatorPerformanceGetParamsLeague.
const (
	GetPerformanceApiV1EmulatorPerformanceGetParamsLeagueMLB     GetPerformanceApiV1EmulatorPerformanceGetParamsLeague = "MLB"
	GetPerformanceApiV1EmulatorPerformanceGetParamsLeagueNBA     GetPerformanceApiV1EmulatorPerformanceGetParamsLeague = "NBA"
	GetPerformanceApiV1EmulatorPerformanceGetParamsLeagueNCAABB  GetPerformanceApiV1EmulatorPerformanceGetParamsLeague = "NCAA_BB"
	GetPerformanceApiV1EmulatorPerformanceGetParamsLeagueNCAABSB GetPerformanceApiV1EmulatorPerformanceGetParamsLeague = "NCAA_BSB"
	GetPerformanceApiV1EmulatorPerformanceGetParamsLeagueNCAAFB  GetPerformanceApiV1EmulatorPerformanceGetParamsLeague = "NCAA_FB"
	GetPerformanceApiV1EmulatorPerformanceGetParamsLeagueNFL     GetPerformanceApiV1EmulatorPerformanceGetParamsLeague = "NFL"
)

// Defines values for GetPerformanceApiV1EmulatorPerformanceGetParamsMarketType.
const (
	GetPerformanceApiV1EmulatorPerformanceGetParamsMarketTypeMONEYLINE GetPerformanceApiV1EmulatorPerformanceGetParamsMarketType = "MONEYLINE"
	GetPerformanceApiV1EmulatorPerformanceGetParamsMarketTypeSPREAD    GetPerformanceApiV1EmulatorPerformanceGetParamsMarketType = "SPREAD"
	GetPerformanceApiV1EmulatorPerformanceGetParamsMarketTypeTOTAL     GetPerformanceApiV1EmulatorPerformanceGetParamsMarketType = "TOTAL"
)

// Defines values for GetPerformanceApiV1EmulatorPerformanceGetParamsWindow.
const (
	GetPerformanceApiV1EmulatorPerformanceGetParamsWindowAllTime GetPerformanceApiV1EmulatorPerformanceGetParamsWindow = "all_time"
	GetPerformanceApiV1EmulatorPerformanceGetParamsWindowDaily   GetPerformanceApiV1EmulatorPerformanceGetParamsWindow = "daily"
	GetPerformanceApiV1EmulatorPerformanceGetParamsWindowMonthly GetPerformanceApiV1EmulatorPerformanceGetParamsWindow = "monthly"
	GetPerformanceApiV1EmulatorPerformanceGetParamsWindowWeekly  GetPerformanceApiV1EmulatorPerformanceGetParamsWindow = "weekly"
)

// Defines values for GetBreakdownApiV1EmulatorPerformanceBreakdownGetParamsGroupBy.
const (
	GetBreakdownApiV1EmulatorPerformanceBreakdownGetParamsGroupByLeague     GetBreakdownApiV1EmulatorPerformanceBreakdownGetParamsGroupBy = "league"
	GetBreakdownApiV1EmulatorPerformanceBreakdownGetParamsGroupByMarketType GetBreakdownApiV1EmulatorPerformanceBreakdownGetParamsGroupBy = "market_type"
	GetBreakdownApiV1EmulatorPerformanceBreakdownGetParamsGroupByMonth      GetBreakdownApiV1EmulatorPerformanceBreakdownGetParamsGroupBy = "month"
	GetBreakdownApiV1EmulatorPerformanceBreakdownGetParamsGroupBySportsbook GetBreakdownApiV1EmulatorPerformanceBreakdownGetParamsGroupBy = "sportsbook"
)

// Defines values for GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsLeague.
const (
	MLB     GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsLeague = "MLB"
	NBA     GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsLeague = "NBA"
	NCAABB  GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsLeague = "NCAA_BB"
	NCAABSB GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsLeague = "NCAA_BSB"
	NCAAFB  GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsLeague = "NCAA_FB"
	NFL     GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsLeague = "NFL"
)

// Defines values for GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsMarketType.
const (
	GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsMarketTypeMONEYLINE GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsMarketType = "MONEYLINE"
	GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsMarketTypeSPREAD    GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsMarketType = "SPREAD"
	GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsMarketTypeTOTAL     GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsMarketType = "TOTAL"
)

// Defines values for GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsWindow.
const (
	AllTime GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsWindow = "all_time"
	Daily   GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsWindow = "daily"
	Monthly GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsWindow = "monthly"
	Weekly  GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsWindow = "weekly"
)

// BankrollConfigData defines model for BankrollConfigData.
type BankrollConfigData struct {
	KellyEnabled          bool    `json:"kelly_enabled"`
	KellyFraction         float32 `json:"kelly_fraction"`
	MaxBetUnits           float32 `json:"max_bet_units"`
	MaxDailyExposureUnits float32 `json:"max_daily_exposure_units"`
}

// BankrollData defines model for BankrollData.
type BankrollData struct {
	BankrollDollars       float32            `json:"bankroll_dollars"`
	BankrollUnits         float32            `json:"bankroll_units"`
	Config                BankrollConfigData `json:"config"`
	OpenBetsCount         int                `json:"open_bets_count"`
	OpenBetsExposureUnits float32            `json:"open_bets_exposure_units"`
	SnapshotAt            time.Time          `json:"snapshot_at"`
	StartingBankrollUnits float32            `json:"starting_bankroll_units"`
	TotalProfitUnits      float32            `json:"total_profit_units"`
	UnitSizeDollars       float32            `json:"unit_size_dollars"`
}

// BankrollHistoryData defines model for BankrollHistoryData.
type BankrollHistoryData struct {
	Interval  BankrollHistoryDataInterval `json:"interval"`
	Snapshots []HistorySnapshotData       `json:"snapshots"`
}

// BankrollHistoryDataInterval defines model for BankrollHistoryData.Interval.
type BankrollHistoryDataInterval string

// BetData defines model for BetData.
type BetData struct {
	Clv                  *float32            `json:"clv"`
	EdgeId               *openapi_types.UUID `json:"edge_id"`
	EdgePercentage       float32             `json:"edge_percentage"`
	GameExternalId       string              `json:"game_external_id"`
	GameId               openapi_types.UUID  `json:"game_id"`
	GradedAt             *time.Time          `json:"graded_at"`
	Id                   openapi_types.UUID  `json:"id"`
	KellyFraction        float32             `json:"kelly_fraction"`
	LineValue            *float32            `json:"line_value"`
	MarketType           string              `json:"market_type"`
	OddsAmerican         int                 `json:"odds_american"`
	OddsDecimal          float32             `json:"odds_decimal"`
	PlacedAt             time.Time           `json:"placed_at"`
	PredictedProbability float32             `json:"predicted_probability"`
	PredictionId         *openapi_types.UUID `json:"prediction_id"`
	ProfitLoss           *float32            `json:"profit_loss"`
	ProfitLossDollars    *float32            `json:"profit_loss_dollars"`
	Reasoning            *string             `json:"reasoning"`
	Result               BetDataResult       `json:"result"`
	Selection            string              `json:"selection"`
	Side                 string              `json:"side"`
	SportsbookId         *openapi_types.UUID `json:"sportsbook_id"`
	SportsbookKey        string              `json:"sportsbook_key"`
	Stake                float32             `json:"stake"`
	StakeDollars         float32             `json:"stake_dollars"`
}

// BetDataResult defines model for BetData.Result.
type BetDataResult string

// BetDetailData defines model for BetDetailData.
type BetDetailData struct {
	ClosingLineValue     *float32            `json:"closing_line_value"`
	ClosingOddsAmerican  *int                `json:"closing_odds_american"`
	Clv                  *float32            `json:"clv"`
	EdgeId               *openapi_types.UUID `json:"edge_id"`
	EdgePercentage       float32             `json:"edge_percentage"`
	GameExternalId       string              `json:"game_external_id"`
	GameId               openapi_types.UUID  `json:"game_id"`
	Grade                *GradeData          `json:"grade"`
	GradedAt             *time.Time          `json:"graded_at"`
	Id                   openapi_types.UUID  `json:"id"`
	KellyFraction        float32             `json:"kelly_fraction"`
	LineValue            *float32            `json:"line_value"`
	MarketType           string              `json:"market_type"`
	OddsAmerican         int                 `json:"odds_american"`
	OddsDecimal          float32             `json:"odds_decimal"`
	PlacedAt             time.Time           `json:"placed_at"`
	PredictedProbability float32             `json:"predicted_probability"`
	PredictionId         *openapi_types.UUID `json:"prediction_id"`
	ProfitLoss           *float32            `json:"profit_loss"`
	ProfitLossDollars    *float32            `json:"profit_loss_dollars"`
	Reasoning            *string             `json:"reasoning"`
	Result               BetDetailDataResult `json:"result"`
	Selection            string              `json:"selection"`
	Side                 string              `json:"side"`
	SportsbookId         *openapi_types.UUID `json:"sportsbook_id"`
	SportsbookKey        string              `json:"sportsbook_key"`
	Stake                float32             `json:"stake"`
	StakeDollars         float32             `json:"stake_dollars"`
}

// BetDetailDataResult defines model for BetDetailData.Result.
type BetDetailDataResult string

// BreakdownData defines model for BreakdownData.
type BreakdownData struct {
	Breakdowns []BreakdownEntry     `json:"breakdowns"`
	GroupBy    BreakdownDataGroupBy `json:"group_by"`
}

// BreakdownDataGroupBy defines model for BreakdownData.GroupBy.
type BreakdownDataGroupBy string

// BreakdownEntry defines model for BreakdownEntry.
type BreakdownEntry struct {
	AvgClv            *float32 `json:"avg_clv"`
	AvgEdgePercentage *float32 `json:"avg_edge_percentage"`
	Group             string   `json:"group"`
	Losses            int      `json:"losses"`
	Pushes            int      `json:"pushes"`
	Roi               float32  `json:"roi"`
	TotalBets         int      `json:"total_bets"`
	TotalProfitUnits  float32  `json:"total_profit_units"`
	WinRate           float32  `json:"win_rate"`
	Wins              int      `json:"wins"`
}

// CalibrationBinData defines model for CalibrationBinData.
type CalibrationBinData struct {
	ActualWinRate           *float32 `json:"actual_win_rate"`
	AvgPredictedProbability *float32 `json:"avg_predicted_probability"`
	BetCount                int      `json:"bet_count"`
	Lower                   float32  `json:"lower"`
	Upper                   float32  `json:"upper"`
}

// CalibrationData defines model for CalibrationData.
type CalibrationData struct {
	Bins             []CalibrationBinData `json:"bins"`
	BrierScore       *float32             `json:"brier_score"`
	CalibrationError *float32             `json:"calibration_error"`
	NBins            int                  `json:"n_bins"`
	Period           PeriodData           `json:"period"`
	TotalGraded      int                  `json:"total_graded"`
}

// EnvelopeBankrollData defines model for Envelope_BankrollData_.
type EnvelopeBankrollData struct {
	Data BankrollData `json:"data"`
	Meta Meta         `json:"meta"`
}

// EnvelopeBankrollHistoryData defines model for Envelope_BankrollHistoryData_.
type EnvelopeBankrollHistoryData struct {
	Data BankrollHistoryData `json:"data"`
	Meta Meta                `json:"meta"`
}

// EnvelopeBetData defines model for Envelope_BetData_.
type EnvelopeBetData struct {
	Data BetData `json:"data"`
	Meta Meta    `json:"meta"`
}

// EnvelopeBetDetailData defines model for Envelope_BetDetailData_.
type EnvelopeBetDetailData struct {
	Data BetDetailData `json:"data"`
	Meta Meta          `json:"meta"`
}

// EnvelopeBreakdownData defines model for Envelope_BreakdownData_.
type EnvelopeBreakdownData struct {
	Data BreakdownData `json:"data"`
	Meta Meta          `json:"meta"`
}

// EnvelopeCalibrationData defines model for Envelope_CalibrationData_.
type EnvelopeCalibrationData struct {
	Data CalibrationData `json:"data"`
	Meta Meta            `json:"meta"`
}

// EnvelopeHealthData defines model for Envelope_HealthData_.
type EnvelopeHealthData struct {
	Data HealthData `json:"data"`
	Meta Meta       `json:"meta"`
}

// EnvelopePerformanceData defines model for Envelope_PerformanceData_.
type EnvelopePerformanceData struct {
	Data PerformanceData `json:"data"`
	Meta Meta            `json:"meta"`
}

// GradeData defines model for GradeData.
type GradeData struct {
	ActualAwayScore   *int                `json:"actual_away_score"`
	ActualHomeScore   *int                `json:"actual_home_score"`
	ActualMargin      *int                `json:"actual_margin"`
	ActualTotal       *int                `json:"actual_total"`
	GameResultId      *openapi_types.UUID `json:"game_result_id"`
	GradedAt          time.Time           `json:"graded_at"`
	Id                openapi_types.UUID  `json:"id"`
	Result            GradeDataResult     `json:"result"`
	ResultDescription string              `json:"result_description"`
}

// GradeDataResult defines model for GradeData.Result.
type GradeDataResult string

// GradeRequest defines model for GradeRequest.
type GradeRequest struct {
	Force *bool `json:"force,omitempty"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// HealthData defines model for HealthData.
type HealthData struct {
	Dependencies  map[string]string `json:"dependencies"`
	Service       *string           `json:"service,omitempty"`
	Stats         HealthStats       `json:"stats"`
	Status        string            `json:"status"`
	Subscriber    string            `json:"subscriber"`
	UptimeSeconds int               `json:"uptime_seconds"`
	Version       string            `json:"version"`
}

// HealthStats defines model for HealthStats.
type HealthStats struct {
	BetsToday   int `json:"bets_today"`
	GradedToday int `json:"graded_today"`
	OpenBets    int `json:"open_bets"`
}

// HistorySnapshotData defines model for HistorySnapshotData.
type HistorySnapshotData struct {
	AvgClv          *float32  `json:"avg_clv"`
	BankrollDollars float32   `json:"bankroll_dollars"`
	BankrollUnits   float32   `json:"bankroll_units"`
	Roi             float32   `json:"roi"`
	Timestamp       time.Time `json:"timestamp"`
	TotalBets       int       `json:"total_bets"`
	TotalLosses     int       `json:"total_losses"`
	TotalWins       int       `json:"total_wins"`
	UnitsWon        float32   `json:"units_won"`
	WinRate         float32   `json:"win_rate"`
}

// Meta defines model for Meta.
type Meta struct {
	RequestId string    `json:"request_id"`
	Timestamp time.Time `json:"timestamp"`
}

// PagedEnvelopeListBetData defines model for PagedEnvelope_list_BetData__.
type PagedEnvelopeListBetData struct {
	Data []BetData `json:"data"`
	Meta PagedMeta `json:"meta"`
}

// PagedMeta defines model for PagedMeta.
type PagedMeta struct {
	Pagination Pagination `json:"pagination"`
	RequestId  string     `json:"request_id"`
	Timestamp  time.Time  `json:"timestamp"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	HasMore    bool    `json:"has_more"`
	Limit      int     `json:"limit"`
	NextCursor *string `json:"next_cursor"`
}

// PerformanceData defines model for PerformanceData.
type PerformanceData struct {
	AvgClv              *float32   `json:"avg_clv"`
	AvgEdgePercentage   *float32   `json:"avg_edge_percentage"`
	AvgOddsAmerican     *int       `json:"avg_odds_american"`
	BrierScore          *float32   `json:"brier_score"`
	CalibrationError    *float32   `json:"calibration_error"`
	LongestLossStreak   int        `json:"longest_loss_streak"`
	LongestWinStreak    int        `json:"longest_win_streak"`
	Period              PeriodData `json:"period"`
	Roi                 float32    `json:"roi"`
	TotalBets           int        `json:"total_bets"`
	TotalLosses         int        `json:"total_losses"`
	TotalProfitDollars  float32    `json:"total_profit_dollars"`
	TotalProfitUnits    float32    `json:"total_profit_units"`
	TotalPushes         int        `json:"total_pushes"`
	TotalWageredDollars float32    `json:"total_wagered_dollars"`
	TotalWageredUnits   float32    `json:"total_wagered_units"`
	TotalWins           int        `json:"total_wins"`
	WinRate             float32    `json:"win_rate"`
}

// PeriodData defines model for PeriodData.
type PeriodData struct {
	From   *time.Time       `json:"from"`
	To     time.Time        `json:"to"`
	Window PeriodDataWindow `json:"window"`
}

// PeriodDataWindow defines model for PeriodData.Window.
type PeriodDataWindow string

// PlaceBetRequest defines model for PlaceBetRequest.
type PlaceBetRequest struct {
	EdgeId *openapi_types.UUID `json:"edge_id"`

	// EdgePercentage Edge in percentage points (4.2 = 4.2%).
	EdgePercentage       float32                   `json:"edge_percentage"`
	GameExternalId       *string                   `json:"game_external_id"`
	GameId               openapi_types.UUID        `json:"game_id"`
	KellyFraction        *float32                  `json:"kelly_fraction"`
	MarketType           PlaceBetRequestMarketType `json:"market_type"`
	PredictedProbability float32                   `json:"predicted_probability"`
	PredictionId         *openapi_types.UUID       `json:"prediction_id"`
	Reasoning            *string                   `json:"reasoning"`
	Selection            string                    `json:"selection"`
	Side                 PlaceBetRequestSide       `json:"side"`
	SportsbookKey        *string                   `json:"sportsbook_key"`

	// Stake Stake in units. Must fit the available bankroll (checked at placement).
	Stake float32 `json:"stake"`
}

// PlaceBetRequestMarketType defines model for PlaceBetRequest.MarketType.
type PlaceBetRequestMarketType string

// PlaceBetRequestSide defines model for PlaceBetRequest.Side.
type PlaceBetRequestSide string

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input *interface{}               `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParams defines parameters for GetBankrollHistoryApiV1EmulatorBankrollHistoryGet.
type GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParams struct {
	// DateFrom Start date (ISO 8601). Default: 30 days ago.
	DateFrom *time.Time `form:"date_from,omitempty" json:"date_from,omitempty"`

	// DateTo End date (ISO 8601). Default: now.
	DateTo *time.Time `form:"date_to,omitempty" json:"date_to,omitempty"`

	// Interval per_bet, daily, or weekly.
	Interval *GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParamsInterval `form:"interval,omitempty" json:"interval,omitempty"`
}

// GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParamsInterval defines parameters for GetBankrollHistoryApiV1EmulatorBankrollHistoryGet.
type GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParamsInterval string

// ListBetsApiV1EmulatorBetsGetParams defines parameters for ListBetsApiV1EmulatorBetsGet.
type ListBetsApiV1EmulatorBetsGetParams struct {
	// League Filter by league.
	League *ListBetsApiV1EmulatorBetsGetParamsLeague `form:"league,omitempty" json:"league,omitempty"`

	// MarketType Filter by market type.
	MarketType *ListBetsApiV1EmulatorBetsGetParamsMarketType `form:"market_type,omitempty" json:"market_type,omitempty"`

	// Result Filter by result.
	Result *ListBetsApiV1EmulatorBetsGetParamsResult `form:"result,omitempty" json:"result,omitempty"`

	// DateFrom Start date (ISO 8601), inclusive, on placed_at.
	DateFrom *time.Time `form:"date_from,omitempty" json:"date_from,omitempty"`

	// DateTo End date (ISO 8601), inclusive, on placed_at.
	DateTo *time.Time `form:"date_to,omitempty" json:"date_to,omitempty"`

	// MinEdge Minimum edge percentage.
	MinEdge *float32 `form:"min_edge,omitempty" json:"min_edge,omitempty"`

	// Status open for pending, graded for completed, or all.
	Status *ListBetsApiV1EmulatorBetsGetParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Limit Max results per page.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListBetsApiV1EmulatorBetsGetParamsLeague defines parameters for ListBetsApiV1EmulatorBetsGet.
type ListBetsApiV1EmulatorBetsGetParamsLeague string

// ListBetsApiV1EmulatorBetsGetParamsMarketType defines parameters for ListBetsApiV1EmulatorBetsGet.
type ListBetsApiV1EmulatorBetsGetParamsMarketType string

// ListBetsApiV1EmulatorBetsGetParamsResult defines parameters for ListBetsApiV1EmulatorBetsGet.
type ListBetsApiV1EmulatorBetsGetParamsResult string

// ListBetsApiV1EmulatorBetsGetParamsStatus defines parameters for ListBetsApiV1EmulatorBetsGet.
type ListBetsApiV1EmulatorBetsGetParamsStatus string

// PlaceBetApiV1EmulatorBetsPostParams defines parameters for PlaceBetApiV1EmulatorBetsPost.
type PlaceBetApiV1EmulatorBetsPostParams struct {
	// XIdempotencyKey UUID preventing duplicate placement on retries.
	XIdempotencyKey string `json:"x-idempotency-key"`
}

// GradeBetApiV1EmulatorBetsBetIdGradePostJSONBody defines parameters for GradeBetApiV1EmulatorBetsBetIdGradePost.
type GradeBetApiV1EmulatorBetsBetIdGradePostJSONBody = GradeRequest

// GetPerformanceApiV1EmulatorPerformanceGetParams defines parameters for GetPerformanceApiV1EmulatorPerformanceGet.
type GetPerformanceApiV1EmulatorPerformanceGetParams struct {
	// League Filter by league.
	League *GetPerformanceApiV1EmulatorPerformanceGetParamsLeague `form:"league,omitempty" json:"league,omitempty"`

	// MarketType Filter by market type.
	MarketType *GetPerformanceApiV1EmulatorPerformanceGetParamsMarketType `form:"market_type,omitempty" json:"market_type,omitempty"`

	// DateFrom Start date (ISO 8601) on placed_at.
	DateFrom *time.Time `form:"date_from,omitempty" json:"date_from,omitempty"`

	// DateTo End date (ISO 8601) on placed_at.
	DateTo *time.Time `form:"date_to,omitempty" json:"date_to,omitempty"`

	// Window Rolling window applied to graded_at.
	Window *GetPerformanceApiV1EmulatorPerformanceGetParamsWindow `form:"window,omitempty" json:"window,omitempty"`
}

// GetPerformanceApiV1EmulatorPerformanceGetParamsLeague defines parameters for GetPerformanceApiV1EmulatorPerformanceGet.
type GetPerformanceApiV1EmulatorPerformanceGetParamsLeague string

// GetPerformanceApiV1EmulatorPerformanceGetParamsMarketType defines parameters for GetPerformanceApiV1EmulatorPerformanceGet.
type GetPerformanceApiV1EmulatorPerformanceGetParamsMarketType string

// GetPerformanceApiV1EmulatorPerformanceGetParamsWindow defines parameters for GetPerformanceApiV1EmulatorPerformanceGet.
type GetPerformanceApiV1EmulatorPerformanceGetParamsWindow string

// GetBreakdownApiV1EmulatorPerformanceBreakdownGetParams defines parameters for GetBreakdownApiV1EmulatorPerformanceBreakdownGet.
type GetBreakdownApiV1EmulatorPerformanceBreakdownGetParams struct {
	// GroupBy Grouping dimension.
	GroupBy *GetBreakdownApiV1EmulatorPerformanceBreakdownGetParamsGroupBy `form:"group_by,omitempty" json:"group_by,omitempty"`

	// DateFrom Start date (ISO 8601) on placed_at.
	DateFrom *time.Time `form:"date_from,omitempty" json:"date_from,omitempty"`

	// DateTo End date (ISO 8601) on placed_at.
	DateTo *time.Time `form:"date_to,omitempty" json:"date_to,omitempty"`
}

// GetBreakdownApiV1EmulatorPerformanceBreakdownGetParamsGroupBy defines parameters for GetBreakdownApiV1EmulatorPerformanceBreakdownGet.
type GetBreakdownApiV1EmulatorPerformanceBreakdownGetParamsGroupBy string

// GetCalibrationApiV1EmulatorPerformanceCalibrationGetParams defines parameters for GetCalibrationApiV1EmulatorPerformanceCalibrationGet.
type GetCalibrationApiV1EmulatorPerformanceCalibrationGetParams struct {
	// League Filter by league.
	League *GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsLeague `form:"league,omitempty" json:"league,omitempty"`

	// MarketType Filter by market type.
	MarketType *GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsMarketType `form:"market_type,omitempty" json:"market_type,omitempty"`

	// DateFrom Start date (ISO 8601) on placed_at.
	DateFrom *time.Time `form:"date_from,omitempty" json:"date_from,omitempty"`

	// DateTo End date (ISO 8601) on placed_at.
	DateTo *time.Time `form:"date_to,omitempty" json:"date_to,omitempty"`

	// Window Rolling window applied to graded_at.
	Window *GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsWindow `form:"window,omitempty" json:"window,omitempty"`

	// Bins Number of equal-width probability bins.
	Bins *int `form:"bins,omitempty" json:"bins,omitempty"`
}

// GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsLeague defines parameters for GetCalibrationApiV1EmulatorPerformanceCalibrationGet.
type GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsLeague string

// GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsMarketType defines parameters for GetCalibrationApiV1EmulatorPerformanceCalibrationGet.
type GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsMarketType string

// GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsWindow defines parameters for GetCalibrationApiV1EmulatorPerformanceCalibrationGet.
type GetCalibrationApiV1EmulatorPerformanceCalibrationGetParamsWindow string

// PlaceBetApiV1EmulatorBetsPostJSONRequestBody defines body for PlaceBetApiV1EmulatorBetsPost for application/json ContentType.
type PlaceBetApiV1EmulatorBetsPostJSONRequestBody = PlaceBetRequest

// GradeBetApiV1EmulatorBetsBetIdGradePostJSONRequestBody defines body for GradeBetApiV1EmulatorBetsBetIdGradePost for application/json ContentType.
type GradeBetApiV1EmulatorBetsBetIdGradePostJSONRequestBody = GradeBetApiV1EmulatorBetsBetIdGradePostJSONBody

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetBankrollApiV1EmulatorBankrollGet request
	GetBankrollApiV1EmulatorBankrollGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBankrollHistoryApiV1EmulatorBankrollHistoryGet request
	GetBankrollHistoryApiV1EmulatorBankrollHistoryGet(ctx context.Context, params *GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListBetsApiV1EmulatorBetsGet request
	ListBetsApiV1EmulatorBetsGet(ctx context.Context, params *ListBetsApiV1EmulatorBetsGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PlaceBetApiV1EmulatorBetsPostWithBody request with any body
	PlaceBetApiV1EmulatorBetsPostWithBody(ctx context.Context, params *PlaceBetApiV1EmulatorBetsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PlaceBetApiV1EmulatorBetsPost(ctx context.Context, params *PlaceBetApiV1EmulatorBetsPostParams, body PlaceBetApiV1EmulatorBetsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBetApiV1EmulatorBetsBetIdGet request
	GetBetApiV1EmulatorBetsBetIdGet(ctx context.Context, betId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GradeBetApiV1EmulatorBetsBetIdGradePostWithBody request with any body
	GradeBetApiV1EmulatorBetsBetIdGradePostWithBody(ctx context.Context, betId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GradeBetApiV1EmulatorBetsBetIdGradePost(ctx context.Context, betId openapi_types.UUID, body GradeBetApiV1EmulatorBetsBetIdGradePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealthApiV1EmulatorHealthGet request
	GetHealthApiV1EmulatorHealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPerformanceApiV1EmulatorPerformanceGet request
	GetPerformanceApiV1EmulatorPerformanceGet(ctx context.Context, params *GetPerformanceApiV1EmulatorPerformanceGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBreakdownApiV1EmulatorPerformanceBreakdownGet request
	GetBreakdownApiV1EmulatorPerformanceBreakdownGet(ctx context.Context, params *GetBreakdownApiV1EmulatorPerformanceBreakdownGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCalibrationApiV1EmulatorPerformanceCalibrationGet request
	GetCalibrationApiV1EmulatorPerformanceCalibrationGet(ctx context.Context, params *GetCalibrationApiV1EmulatorPerformanceCalibrationGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetBankrollApiV1EmulatorBankrollGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBankrollApiV1EmulatorBankrollGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetBankrollHistoryApiV1EmulatorBankrollHistoryGet(ctx context.Context, params *GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBankrollHistoryApiV1EmulatorBankrollHistoryGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListBetsApiV1EmulatorBetsGet(ctx context.Context, params *ListBetsApiV1EmulatorBetsGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListBetsApiV1EmulatorBetsGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PlaceBetApiV1EmulatorBetsPostWithBody(ctx context.Context, params *PlaceBetApiV1EmulatorBetsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPlaceBetApiV1EmulatorBetsPostRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PlaceBetApiV1EmulatorBetsPost(ctx context.Context, params *PlaceBetApiV1EmulatorBetsPostParams, body PlaceBetApiV1EmulatorBetsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPlaceBetApiV1EmulatorBetsPostRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetBetApiV1EmulatorBetsBetIdGet(ctx context.Context, betId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBetApiV1EmulatorBetsBetIdGetRequest(c.Server, betId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GradeBetApiV1EmulatorBetsBetIdGradePostWithBody(ctx context.Context, betId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGradeBetApiV1EmulatorBetsBetIdGradePostRequestWithBody(c.Server, betId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GradeBetApiV1EmulatorBetsBetIdGradePost(ctx context.Context, betId openapi_types.UUID, body GradeBetApiV1EmulatorBetsBetIdGradePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGradeBetApiV1EmulatorBetsBetIdGradePostRequest(c.Server, betId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealthApiV1EmulatorHealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthApiV1EmulatorHealthGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPerformanceApiV1EmulatorPerformanceGet(ctx context.Context, params *GetPerformanceApiV1EmulatorPerformanceGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPerformanceApiV1EmulatorPerformanceGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetBreakdownApiV1EmulatorPerformanceBreakdownGet(ctx context.Context, params *GetBreakdownApiV1EmulatorPerformanceBreakdownGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBreakdownApiV1EmulatorPerformanceBreakdownGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCalibrationApiV1EmulatorPerformanceCalibrationGet(ctx context.Context, params *GetCalibrationApiV1EmulatorPerformanceCalibrationGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCalibrationApiV1EmulatorPerformanceCalibrationGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetBankrollApiV1EmulatorBankrollGetRequest generates requests for GetBankrollApiV1EmulatorBankrollGet
func NewGetBankrollApiV1EmulatorBankrollGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/emulator/bankroll")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetBankrollHistoryApiV1EmulatorBankrollHistoryGetRequest generates requests for GetBankrollHistoryApiV1EmulatorBankrollHistoryGet
func NewGetBankrollHistoryApiV1EmulatorBankrollHistoryGetRequest(server string, params *GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/emulator/bankroll/history")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.DateFrom != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "date_from", runtime.ParamLocationQuery, *params.DateFrom); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.DateTo != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "date_to", runtime.ParamLocationQuery, *params.DateTo); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Interval != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "interval", runtime.ParamLocationQuery, *params.Interval); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListBetsApiV1EmulatorBetsGetRequest generates requests for ListBetsApiV1EmulatorBetsGet
func NewListBetsApiV1EmulatorBetsGetRequest(server string, params *ListBetsApiV1EmulatorBetsGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/emulator/bets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.League != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "league", runtime.ParamLocationQuery, *params.League); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MarketType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "market_type", runtime.ParamLocationQuery, *params.MarketType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Result != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "result", runtime.ParamLocationQuery, *params.Result); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.DateFrom != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "date_from", runtime.ParamLocationQuery, *params.DateFrom); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.DateTo != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "date_to", runtime.ParamLocationQuery, *params.DateTo); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MinEdge != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "min_edge", runtime.ParamLocationQuery, *params.MinEdge); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "status", runtime.ParamLocationQuery, *params.Status); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPlaceBetApiV1EmulatorBetsPostRequest calls the generic PlaceBetApiV1EmulatorBetsPost builder with application/json body
func NewPlaceBetApiV1EmulatorBetsPostRequest(server string, params *PlaceBetApiV1EmulatorBetsPostParams, body PlaceBetApiV1EmulatorBetsPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPlaceBetApiV1EmulatorBetsPostRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPlaceBetApiV1EmulatorBetsPostRequestWithBody generates requests for PlaceBetApiV1EmulatorBetsPost with any type of body
func NewPlaceBetApiV1EmulatorBetsPostRequestWithBody(server string, params *PlaceBetApiV1EmulatorBetsPostParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/emulator/bets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "x-idempotency-key", runtime.ParamLocationHeader, params.XIdempotencyKey)
		if err != nil {
			return nil, err
		}

		req.Header.Set("x-idempotency-key", headerParam0)

	}

	return req, nil
}

// NewGetBetApiV1EmulatorBetsBetIdGetRequest generates requests for GetBetApiV1EmulatorBetsBetIdGet
func NewGetBetApiV1EmulatorBetsBetIdGetRequest(server string, betId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bet_id", runtime.ParamLocationPath, betId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/emulator/bets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGradeBetApiV1EmulatorBetsBetIdGradePostRequest calls the generic GradeBetApiV1EmulatorBetsBetIdGradePost builder with application/json body
func NewGradeBetApiV1EmulatorBetsBetIdGradePostRequest(server string, betId openapi_types.UUID, body GradeBetApiV1EmulatorBetsBetIdGradePostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGradeBetApiV1EmulatorBetsBetIdGradePostRequestWithBody(server, betId, "application/json", bodyReader)
}

// NewGradeBetApiV1EmulatorBetsBetIdGradePostRequestWithBody generates requests for GradeBetApiV1EmulatorBetsBetIdGradePost with any type of body
func NewGradeBetApiV1EmulatorBetsBetIdGradePostRequestWithBody(server string, betId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bet_id", runtime.ParamLocationPath, betId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/emulator/bets/%s/grade", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetHealthApiV1EmulatorHealthGetRequest generates requests for GetHealthApiV1EmulatorHealthGet
func NewGetHealthApiV1EmulatorHealthGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/emulator/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPerformanceApiV1EmulatorPerformanceGetRequest generates requests for GetPerformanceApiV1EmulatorPerformanceGet
func NewGetPerformanceApiV1EmulatorPerformanceGetRequest(server string, params *GetPerformanceApiV1EmulatorPerformanceGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/emulator/performance")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.League != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "league", runtime.ParamLocationQuery, *params.League); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MarketType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "market_type", runtime.ParamLocationQuery, *params.MarketType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.DateFrom != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "date_from", runtime.ParamLocationQuery, *params.DateFrom); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.DateTo != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "date_to", runtime.ParamLocationQuery, *params.DateTo); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Window != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "window", runtime.ParamLocationQuery, *params.Window); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetBreakdownApiV1EmulatorPerformanceBreakdownGetRequest generates requests for GetBreakdownApiV1EmulatorPerformanceBreakdownGet
func NewGetBreakdownApiV1EmulatorPerformanceBreakdownGetRequest(server string, params *GetBreakdownApiV1EmulatorPerformanceBreakdownGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/emulator/performance/breakdown")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.GroupBy != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "group_by", runtime.ParamLocationQuery, *params.GroupBy); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.DateFrom != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "date_from", runtime.ParamLocationQuery, *params.DateFrom); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.DateTo != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "date_to", runtime.ParamLocationQuery, *params.DateTo); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCalibrationApiV1EmulatorPerformanceCalibrationGetRequest generates requests for GetCalibrationApiV1EmulatorPerformanceCalibrationGet
func NewGetCalibrationApiV1EmulatorPerformanceCalibrationGetRequest(server string, params *GetCalibrationApiV1EmulatorPerformanceCalibrationGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/emulator/performance/calibration")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.League != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "league", runtime.ParamLocationQuery, *params.League); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MarketType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "market_type", runtime.ParamLocationQuery, *params.MarketType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.DateFrom != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "date_from", runtime.ParamLocationQuery, *params.DateFrom); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.DateTo != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "date_to", runtime.ParamLocationQuery, *params.DateTo); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Window != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "window", runtime.ParamLocationQuery, *params.Window); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Bins != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "bins", runtime.ParamLocationQuery, *params.Bins); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetBankrollApiV1EmulatorBankrollGetWithResponse request
	GetBankrollApiV1EmulatorBankrollGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetBankrollApiV1EmulatorBankrollGetResponse, error)

	// GetBankrollHistoryApiV1EmulatorBankrollHistoryGetWithResponse request
	GetBankrollHistoryApiV1EmulatorBankrollHistoryGetWithResponse(ctx context.Context, params *GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParams, reqEditors ...RequestEditorFn) (*GetBankrollHistoryApiV1EmulatorBankrollHistoryGetResponse, error)

	// ListBetsApiV1EmulatorBetsGetWithResponse request
	ListBetsApiV1EmulatorBetsGetWithResponse(ctx context.Context, params *ListBetsApiV1EmulatorBetsGetParams, reqEditors ...RequestEditorFn) (*ListBetsApiV1EmulatorBetsGetResponse, error)

	// PlaceBetApiV1EmulatorBetsPostWithBodyWithResponse request with any body
	PlaceBetApiV1EmulatorBetsPostWithBodyWithResponse(ctx context.Context, params *PlaceBetApiV1EmulatorBetsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PlaceBetApiV1EmulatorBetsPostResponse, error)

	PlaceBetApiV1EmulatorBetsPostWithResponse(ctx context.Context, params *PlaceBetApiV1EmulatorBetsPostParams, body PlaceBetApiV1EmulatorBetsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*PlaceBetApiV1EmulatorBetsPostResponse, error)

	// GetBetApiV1EmulatorBetsBetIdGetWithResponse request
	GetBetApiV1EmulatorBetsBetIdGetWithResponse(ctx context.Context, betId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetBetApiV1EmulatorBetsBetIdGetResponse, error)

	// GradeBetApiV1EmulatorBetsBetIdGradePostWithBodyWithResponse request with any body
	GradeBetApiV1EmulatorBetsBetIdGradePostWithBodyWithResponse(ctx context.Context, betId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GradeBetApiV1EmulatorBetsBetIdGradePostResponse, error)

	GradeBetApiV1EmulatorBetsBetIdGradePostWithResponse(ctx context.Context, betId openapi_types.UUID, body GradeBetApiV1EmulatorBetsBetIdGradePostJSONRequestBody, reqEditors ...RequestEditorFn) (*GradeBetApiV1EmulatorBetsBetIdGradePostResponse, error)

	// GetHealthApiV1EmulatorHealthGetWithResponse request
	GetHealthApiV1EmulatorHealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthApiV1EmulatorHealthGetResponse, error)

	// GetPerformanceApiV1EmulatorPerformanceGetWithResponse request
	GetPerformanceApiV1EmulatorPerformanceGetWithResponse(ctx context.Context, params *GetPerformanceApiV1EmulatorPerformanceGetParams, reqEditors ...RequestEditorFn) (*GetPerformanceApiV1EmulatorPerformanceGetResponse, error)

	// GetBreakdownApiV1EmulatorPerformanceBreakdownGetWithResponse request
	GetBreakdownApiV1EmulatorPerformanceBreakdownGetWithResponse(ctx context.Context, params *GetBreakdownApiV1EmulatorPerformanceBreakdownGetParams, reqEditors ...RequestEditorFn) (*GetBreakdownApiV1EmulatorPerformanceBreakdownGetResponse, error)

	// GetCalibrationApiV1EmulatorPerformanceCalibrationGetWithResponse request
	GetCalibrationApiV1EmulatorPerformanceCalibrationGetWithResponse(ctx context.Context, params *GetCalibrationApiV1EmulatorPerformanceCalibrationGetParams, reqEditors ...RequestEditorFn) (*GetCalibrationApiV1EmulatorPerformanceCalibrationGetResponse, error)
}

type GetBankrollApiV1EmulatorBankrollGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeBankrollData
}

// Status returns HTTPResponse.Status
func (r GetBankrollApiV1EmulatorBankrollGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBankrollApiV1EmulatorBankrollGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetBankrollHistoryApiV1EmulatorBankrollHistoryGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeBankrollHistoryData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetBankrollHistoryApiV1EmulatorBankrollHistoryGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBankrollHistoryApiV1EmulatorBankrollHistoryGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListBetsApiV1EmulatorBetsGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PagedEnvelopeListBetData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r ListBetsApiV1EmulatorBetsGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListBetsApiV1EmulatorBetsGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PlaceBetApiV1EmulatorBetsPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *EnvelopeBetData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r PlaceBetApiV1EmulatorBetsPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PlaceBetApiV1EmulatorBetsPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetBetApiV1EmulatorBetsBetIdGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeBetDetailData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetBetApiV1EmulatorBetsBetIdGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBetApiV1EmulatorBetsBetIdGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GradeBetApiV1EmulatorBetsBetIdGradePostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeBetDetailData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GradeBetApiV1EmulatorBetsBetIdGradePostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GradeBetApiV1EmulatorBetsBetIdGradePostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthApiV1EmulatorHealthGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeHealthData
}

// Status returns HTTPResponse.Status
func (r GetHealthApiV1EmulatorHealthGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthApiV1EmulatorHealthGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPerformanceApiV1EmulatorPerformanceGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopePerformanceData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetPerformanceApiV1EmulatorPerformanceGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPerformanceApiV1EmulatorPerformanceGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetBreakdownApiV1EmulatorPerformanceBreakdownGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeBreakdownData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetBreakdownApiV1EmulatorPerformanceBreakdownGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBreakdownApiV1EmulatorPerformanceBreakdownGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCalibrationApiV1EmulatorPerformanceCalibrationGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeCalibrationData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetCalibrationApiV1EmulatorPerformanceCalibrationGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCalibrationApiV1EmulatorPerformanceCalibrationGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetBankrollApiV1EmulatorBankrollGetWithResponse request returning *GetBankrollApiV1EmulatorBankrollGetResponse
func (c *ClientWithResponses) GetBankrollApiV1EmulatorBankrollGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetBankrollApiV1EmulatorBankrollGetResponse, error) {
	rsp, err := c.GetBankrollApiV1EmulatorBankrollGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBankrollApiV1EmulatorBankrollGetResponse(rsp)
}

// GetBankrollHistoryApiV1EmulatorBankrollHistoryGetWithResponse request returning *GetBankrollHistoryApiV1EmulatorBankrollHistoryGetResponse
func (c *ClientWithResponses) GetBankrollHistoryApiV1EmulatorBankrollHistoryGetWithResponse(ctx context.Context, params *GetBankrollHistoryApiV1EmulatorBankrollHistoryGetParams, reqEditors ...RequestEditorFn) (*GetBankrollHistoryApiV1EmulatorBankrollHistoryGetResponse, error) {
	rsp, err := c.GetBankrollHistoryApiV1EmulatorBankrollHistoryGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBankrollHistoryApiV1EmulatorBankrollHistoryGetResponse(rsp)
}

// ListBetsApiV1EmulatorBetsGetWithResponse request returning *ListBetsApiV1EmulatorBetsGetResponse
func (c *ClientWithResponses) ListBetsApiV1EmulatorBetsGetWithResponse(ctx context.Context, params *ListBetsApiV1EmulatorBetsGetParams, reqEditors ...RequestEditorFn) (*ListBetsApiV1EmulatorBetsGetResponse, error) {
	rsp, err := c.ListBetsApiV1EmulatorBetsGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListBetsApiV1EmulatorBetsGetResponse(rsp)
}

// PlaceBetApiV1EmulatorBetsPostWithBodyWithResponse request with arbitrary body returning *PlaceBetApiV1EmulatorBetsPostResponse
func (c *ClientWithResponses) PlaceBetApiV1EmulatorBetsPostWithBodyWithResponse(ctx context.Context, params *PlaceBetApiV1EmulatorBetsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PlaceBetApiV1EmulatorBetsPostResponse, error) {
	rsp, err := c.PlaceBetApiV1EmulatorBetsPostWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePlaceBetApiV1EmulatorBetsPostResponse(rsp)
}

func (c *ClientWithResponses) PlaceBetApiV1EmulatorBetsPostWithResponse(ctx context.Context, params *PlaceBetApiV1EmulatorBetsPostParams, body PlaceBetApiV1EmulatorBetsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*PlaceBetApiV1EmulatorBetsPostResponse, error) {
	rsp, err := c.PlaceBetApiV1EmulatorBetsPost(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePlaceBetApiV1EmulatorBetsPostResponse(rsp)
}

// GetBetApiV1EmulatorBetsBetIdGetWithResponse request returning *GetBetApiV1EmulatorBetsBetIdGetResponse
func (c *ClientWithResponses) GetBetApiV1EmulatorBetsBetIdGetWithResponse(ctx context.Context, betId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetBetApiV1EmulatorBetsBetIdGetResponse, error) {
	rsp, err := c.GetBetApiV1EmulatorBetsBetIdGet(ctx, betId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBetApiV1EmulatorBetsBetIdGetResponse(rsp)
}

// GradeBetApiV1EmulatorBetsBetIdGradePostWithBodyWithResponse request with arbitrary body returning *GradeBetApiV1EmulatorBetsBetIdGradePostResponse
func (c *ClientWithResponses) GradeBetApiV1EmulatorBetsBetIdGradePostWithBodyWithResponse(ctx context.Context, betId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GradeBetApiV1EmulatorBetsBetIdGradePostResponse, error) {
	rsp, err := c.GradeBetApiV1EmulatorBetsBetIdGradePostWithBody(ctx, betId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGradeBetApiV1EmulatorBetsBetIdGradePostResponse(rsp)
}

func (c *ClientWithResponses) GradeBetApiV1EmulatorBetsBetIdGradePostWithResponse(ctx context.Context, betId openapi_types.UUID, body GradeBetApiV1EmulatorBetsBetIdGradePostJSONRequestBody, reqEditors ...RequestEditorFn) (*GradeBetApiV1EmulatorBetsBetIdGradePostResponse, error) {
	rsp, err := c.GradeBetApiV1EmulatorBetsBetIdGradePost(ctx, betId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGradeBetApiV1EmulatorBetsBetIdGradePostResponse(rsp)
}

// GetHealthApiV1EmulatorHealthGetWithResponse request returning *GetHealthApiV1EmulatorHealthGetResponse
func (c *ClientWithResponses) GetHealthApiV1EmulatorHealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthApiV1EmulatorHealthGetResponse, error) {
	rsp, err := c.GetHealthApiV1EmulatorHealthGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthApiV1EmulatorHealthGetResponse(rsp)
}

// GetPerformanceApiV1EmulatorPerformanceGetWithResponse request returning *GetPerformanceApiV1EmulatorPerformanceGetResponse
func (c *ClientWithResponses) GetPerformanceApiV1EmulatorPerformanceGetWithResponse(ctx context.Context, params *GetPerformanceApiV1EmulatorPerformanceGetParams, reqEditors ...RequestEditorFn) (*GetPerformanceApiV1EmulatorPerformanceGetResponse, error) {
	rsp, err := c.GetPerformanceApiV1EmulatorPerformanceGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPerformanceApiV1EmulatorPerformanceGetResponse(rsp)
}

// GetBreakdownApiV1EmulatorPerformanceBreakdownGetWithResponse request returning *GetBreakdownApiV1EmulatorPerformanceBreakdownGetResponse
func (c *ClientWithResponses) GetBreakdownApiV1EmulatorPerformanceBreakdownGetWithResponse(ctx context.Context, params *GetBreakdownApiV1EmulatorPerformanceBreakdownGetParams, reqEditors ...RequestEditorFn) (*GetBreakdownApiV1EmulatorPerformanceBreakdownGetResponse, error) {
	rsp, err := c.GetBreakdownApiV1EmulatorPerformanceBreakdownGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBreakdownApiV1EmulatorPerformanceBreakdownGetResponse(rsp)
}

// GetCalibrationApiV1EmulatorPerformanceCalibrationGetWithResponse request returning *GetCalibrationApiV1EmulatorPerformanceCalibrationGetResponse
func (c *ClientWithResponses) GetCalibrationApiV1EmulatorPerformanceCalibrationGetWithResponse(ctx context.Context, params *GetCalibrationApiV1EmulatorPerformanceCalibrationGetParams, reqEditors ...RequestEditorFn) (*GetCalibrationApiV1EmulatorPerformanceCalibrationGetResponse, error) {
	rsp, err := c.GetCalibrationApiV1EmulatorPerformanceCalibrationGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCalibrationApiV1EmulatorPerformanceCalibrationGetResponse(rsp)
}

// ParseGetBankrollApiV1EmulatorBankrollGetResponse parses an HTTP response from a GetBankrollApiV1EmulatorBankrollGetWithResponse call
func ParseGetBankrollApiV1EmulatorBankrollGetResponse(rsp *http.Response) (*GetBankrollApiV1EmulatorBankrollGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBankrollApiV1EmulatorBankrollGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeBankrollData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetBankrollHistoryApiV1EmulatorBankrollHistoryGetResponse parses an HTTP response from a GetBankrollHistoryApiV1EmulatorBankrollHistoryGetWithResponse call
func ParseGetBankrollHistoryApiV1EmulatorBankrollHistoryGetResponse(rsp *http.Response) (*GetBankrollHistoryApiV1EmulatorBankrollHistoryGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBankrollHistoryApiV1EmulatorBankrollHistoryGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeBankrollHistoryData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseListBetsApiV1EmulatorBetsGetResponse parses an HTTP response from a ListBetsApiV1EmulatorBetsGetWithResponse call
func ParseListBetsApiV1EmulatorBetsGetResponse(rsp *http.Response) (*ListBetsApiV1EmulatorBetsGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListBetsApiV1EmulatorBetsGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PagedEnvelopeListBetData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParsePlaceBetApiV1EmulatorBetsPostResponse parses an HTTP response from a PlaceBetApiV1EmulatorBetsPostWithResponse call
func ParsePlaceBetApiV1EmulatorBetsPostResponse(rsp *http.Response) (*PlaceBetApiV1EmulatorBetsPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PlaceBetApiV1EmulatorBetsPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest EnvelopeBetData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetBetApiV1EmulatorBetsBetIdGetResponse parses an HTTP response from a GetBetApiV1EmulatorBetsBetIdGetWithResponse call
func ParseGetBetApiV1EmulatorBetsBetIdGetResponse(rsp *http.Response) (*GetBetApiV1EmulatorBetsBetIdGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBetApiV1EmulatorBetsBetIdGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeBetDetailData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGradeBetApiV1EmulatorBetsBetIdGradePostResponse parses an HTTP response from a GradeBetApiV1EmulatorBetsBetIdGradePostWithResponse call
func ParseGradeBetApiV1EmulatorBetsBetIdGradePostResponse(rsp *http.Response) (*GradeBetApiV1EmulatorBetsBetIdGradePostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GradeBetApiV1EmulatorBetsBetIdGradePostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeBetDetailData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetHealthApiV1EmulatorHealthGetResponse parses an HTTP response from a GetHealthApiV1EmulatorHealthGetWithResponse call
func ParseGetHealthApiV1EmulatorHealthGetResponse(rsp *http.Response) (*GetHealthApiV1EmulatorHealthGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthApiV1EmulatorHealthGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeHealthData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetPerformanceApiV1EmulatorPerformanceGetResponse parses an HTTP response from a GetPerformanceApiV1EmulatorPerformanceGetWithResponse call
func ParseGetPerformanceApiV1EmulatorPerformanceGetResponse(rsp *http.Response) (*GetPerformanceApiV1EmulatorPerformanceGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPerformanceApiV1EmulatorPerformanceGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopePerformanceData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetBreakdownApiV1EmulatorPerformanceBreakdownGetResponse parses an HTTP response from a GetBreakdownApiV1EmulatorPerformanceBreakdownGetWithResponse call
func ParseGetBreakdownApiV1EmulatorPerformanceBreakdownGetResponse(rsp *http.Response) (*GetBreakdownApiV1EmulatorPerformanceBreakdownGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBreakdownApiV1EmulatorPerformanceBreakdownGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeBreakdownData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetCalibrationApiV1EmulatorPerformanceCalibrationGetResponse parses an HTTP response from a GetCalibrationApiV1EmulatorPerformanceCalibrationGetWithResponse call
func ParseGetCalibrationApiV1EmulatorPerformanceCalibrationGetResponse(rsp *http.Response) (*GetCalibrationApiV1EmulatorPerformanceCalibrationGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCalibrationApiV1EmulatorPerformanceCalibrationGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeCalibrationData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
