// Package agentservice provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package agentservice

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AnalysisRequestAnalysisType.
const (
	EDGEBREAKDOWN     AnalysisRequestAnalysisType = "EDGE_BREAKDOWN"
	GAMEPREVIEW       AnalysisRequestAnalysisType = "GAME_PREVIEW"
	PERFORMANCEREVIEW AnalysisRequestAnalysisType = "PERFORMANCE_REVIEW"
)

// ActiveEdges defines model for ActiveEdges.
type ActiveEdges struct {
	AvgEdgePct float32        `json:"avg_edge_pct"`
	ByLeague   map[string]int `json:"by_league"`
	Count      int            `json:"count"`
	TopEdge    *TopEdge       `json:"top_edge"`
}

// AlertData defines model for AlertData.
type AlertData struct {
	AcknowledgedAt *string                `json:"acknowledged_at"`
	Channel        string                 `json:"channel"`
	DeliveredAt    string                 `json:"delivered_at"`
	EdgeId         string                 `json:"edge_id"`
	Id             string                 `json:"id"`
	Message        string                 `json:"message"`
	Payload        map[string]interface{} `json:"payload"`
	Priority       string                 `json:"priority"`
}

// AllTimePerformance defines model for AllTimePerformance.
type AllTimePerformance struct {
	Bets        int     `json:"bets"`
	ProfitUnits float32 `json:"profit_units"`
	Roi         float32 `json:"roi"`
	WinRate     float32 `json:"win_rate"`
}

// AnalysisData defines model for AnalysisData.
type AnalysisData struct {
	AnalysisType string  `json:"analysis_type"`
	Content      string  `json:"content"`
	CreatedAt    string  `json:"created_at"`
	EdgeId       *string `json:"edge_id"`
	GameId       *string `json:"game_id"`
	Id           string  `json:"id"`
	InputSummary *string `json:"input_summary"`
	ModelUsed    string  `json:"model_used"`
	Title        string  `json:"title"`
}

// AnalysisRequest defines model for AnalysisRequest.
type AnalysisRequest struct {
	AnalysisType AnalysisRequestAnalysisType `json:"analysis_type"`
	EdgeId       *string                     `json:"edge_id"`
	GameId       *string                     `json:"game_id"`
	Question     *string                     `json:"question"`
}

// AnalysisRequestAnalysisType defines model for AnalysisRequest.AnalysisType.
type AnalysisRequestAnalysisType string

// DashboardData defines model for DashboardData.
type DashboardData struct {
	ActiveEdges        ActiveEdges         `json:"active_edges"`
	OpenBets           *OpenBets           `json:"open_bets"`
	PerformanceSummary *PerformanceSummary `json:"performance_summary"`
	PipelineStatus     PipelineStatus      `json:"pipeline_status"`
}

// EdgeAnalysisSummary defines model for EdgeAnalysisSummary.
type EdgeAnalysisSummary struct {
	CreatedAt string `json:"created_at"`
	Id        string `json:"id"`
	Title     string `json:"title"`
}

// EdgeBettingLine defines model for EdgeBettingLine.
type EdgeBettingLine struct {
	Id            string   `json:"id"`
	LineValue     *float32 `json:"line_value"`
	OddsAmerican  int      `json:"odds_american"`
	SportsbookKey string   `json:"sportsbook_key"`
	Timestamp     string   `json:"timestamp"`
}

// EdgeDetailData defines model for EdgeDetailData.
type EdgeDetailData struct {
	Analysis              *EdgeAnalysisSummary `json:"analysis"`
	BettingLine           *EdgeBettingLine     `json:"betting_line"`
	Confidence            *float32             `json:"confidence"`
	DetectedAt            string               `json:"detected_at"`
	EdgePercentage        float32              `json:"edge_percentage"`
	ExpectedValue         float32              `json:"expected_value"`
	ExpiresAt             string               `json:"expires_at"`
	Game                  *EdgeGame            `json:"game"`
	GameId                string               `json:"game_id"`
	Id                    string               `json:"id"`
	ImpliedProbability    float32              `json:"implied_probability"`
	IsStale               bool                 `json:"is_stale"`
	KellyFraction         float32              `json:"kelly_fraction"`
	League                string               `json:"league"`
	MarketType            string               `json:"market_type"`
	OddsAmerican          int                  `json:"odds_american"`
	OddsDecimal           float32              `json:"odds_decimal"`
	PaperBet              *EdgePaperBet        `json:"paper_bet"`
	PredictedProbability  float32              `json:"predicted_probability"`
	Prediction            *EdgePrediction      `json:"prediction"`
	RecommendedStake      float32              `json:"recommended_stake"`
	Selection             string               `json:"selection"`
	SimulationProbability *float32             `json:"simulation_probability"`
	SportsbookId          *string              `json:"sportsbook_id"`
	SportsbookKey         string               `json:"sportsbook_key"`
}

// EdgeGame defines model for EdgeGame.
type EdgeGame struct {
	AwayTeam       EdgeGameTeam `json:"away_team"`
	HomeTeam       EdgeGameTeam `json:"home_team"`
	ScheduledStart string       `json:"scheduled_start"`
	Status         string       `json:"status"`
}

// EdgeGameTeam defines model for EdgeGameTeam.
type EdgeGameTeam struct {
	Abbreviation string `json:"abbreviation"`
	Id           string `json:"id"`
	Name         string `json:"name"`
}

// EdgeListItem defines model for EdgeListItem.
type EdgeListItem struct {
	AwayTeam             *string  `json:"away_team"`
	Confidence           *float32 `json:"confidence"`
	DetectedAt           string   `json:"detected_at"`
	EdgePercentage       float32  `json:"edge_percentage"`
	ExpectedValue        float32  `json:"expected_value"`
	ExpiresAt            string   `json:"expires_at"`
	GameId               string   `json:"game_id"`
	HasPaperBet          bool     `json:"has_paper_bet"`
	HomeTeam             *string  `json:"home_team"`
	Id                   string   `json:"id"`
	ImpliedProbability   float32  `json:"implied_probability"`
	IsStale              bool     `json:"is_stale"`
	KellyFraction        float32  `json:"kelly_fraction"`
	League               string   `json:"league"`
	MarketType           string   `json:"market_type"`
	OddsAmerican         int      `json:"odds_american"`
	PaperBetId           *string  `json:"paper_bet_id"`
	PredictedProbability float32  `json:"predicted_probability"`
	RecommendedStake     float32  `json:"recommended_stake"`
	ScheduledStart       string   `json:"scheduled_start"`
	Selection            string   `json:"selection"`
	SportsbookKey        string   `json:"sportsbook_key"`
}

// EdgePaperBet defines model for EdgePaperBet.
type EdgePaperBet struct {
	Id       string  `json:"id"`
	PlacedAt string  `json:"placed_at"`
	Result   string  `json:"result"`
	Stake    float32 `json:"stake"`
}

// EdgePrediction defines model for EdgePrediction.
type EdgePrediction struct {
	AdjustmentMagnitude float32            `json:"adjustment_magnitude"`
	FeatureImportance   map[string]float32 `json:"feature_importance"`
	Id                  string             `json:"id"`
	ModelVersionId      string             `json:"model_version_id"`
}

// EnvelopeAlertData defines model for Envelope_AlertData_.
type EnvelopeAlertData struct {
	Data AlertData `json:"data"`
	Meta Meta      `json:"meta"`
}

// EnvelopeAnalysisData defines model for Envelope_AnalysisData_.
type EnvelopeAnalysisData struct {
	Data AnalysisData `json:"data"`
	Meta Meta         `json:"meta"`
}

// EnvelopeDashboardData defines model for Envelope_DashboardData_.
type EnvelopeDashboardData struct {
	Data DashboardData `json:"data"`
	Meta Meta          `json:"meta"`
}

// EnvelopeEdgeDetailData defines model for Envelope_EdgeDetailData_.
type EnvelopeEdgeDetailData struct {
	Data EdgeDetailData `json:"data"`
	Meta Meta           `json:"meta"`
}

// EnvelopeHealthData defines model for Envelope_HealthData_.
type EnvelopeHealthData struct {
	Data HealthData `json:"data"`
	Meta Meta       `json:"meta"`
}

// EnvelopePipelineRunAcceptedData defines model for Envelope_PipelineRunAcceptedData_.
type EnvelopePipelineRunAcceptedData struct {
	Data PipelineRunAcceptedData `json:"data"`
	Meta Meta                    `json:"meta"`
}

// EnvelopePipelineRunData defines model for Envelope_PipelineRunData_.
type EnvelopePipelineRunData struct {
	Data PipelineRunData `json:"data"`
	Meta Meta            `json:"meta"`
}

// EnvelopeScheduleData defines model for Envelope_ScheduleData_.
type EnvelopeScheduleData struct {
	Data ScheduleData `json:"data"`
	Meta Meta         `json:"meta"`
}

// EnvelopeScheduleListData defines model for Envelope_ScheduleListData_.
type EnvelopeScheduleListData struct {
	Data ScheduleListData `json:"data"`
	Meta Meta             `json:"meta"`
}

// EnvelopeSlateData defines model for Envelope_SlateData_.
type EnvelopeSlateData struct {
	Data SlateData `json:"data"`
	Meta Meta      `json:"meta"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// HealthData defines model for HealthData.
type HealthData struct {
	Dependencies  map[string]string `json:"dependencies"`
	Pipeline      *HealthPipeline   `json:"pipeline,omitempty"`
	Service       *string           `json:"service,omitempty"`
	Status        string            `json:"status"`
	UptimeSeconds int               `json:"uptime_seconds"`
	Version       string            `json:"version"`
}

// HealthPipeline defines model for HealthPipeline.
type HealthPipeline struct {
	LastRunAt        *string `json:"last_run_at"`
	LastRunStatus    *string `json:"last_run_status"`
	NextScheduledRun *string `json:"next_scheduled_run"`
}

// LastRun defines model for LastRun.
type LastRun struct {
	BetsPlaced     int     `json:"bets_placed"`
	CompletedAt    *string `json:"completed_at"`
	EdgesFound     int     `json:"edges_found"`
	GamesProcessed int     `json:"games_processed"`
	PipelineRunId  string  `json:"pipeline_run_id"`
	Status         string  `json:"status"`
}

// Meta defines model for Meta.
type Meta struct {
	RequestId string    `json:"request_id"`
	Timestamp time.Time `json:"timestamp"`
}

// OpenBets defines model for OpenBets.
type OpenBets struct {
	Count              int     `json:"count"`
	GamesPending       int     `json:"games_pending"`
	TotalExposureUnits float32 `json:"total_exposure_units"`
}

// PageEnvelopeAlertData defines model for PageEnvelope_AlertData_.
type PageEnvelopeAlertData struct {
	Data []AlertData `json:"data"`
	Meta PageMeta    `json:"meta"`
}

// PageEnvelopeEdgeListItem defines model for PageEnvelope_EdgeListItem_.
type PageEnvelopeEdgeListItem struct {
	Data []EdgeListItem `json:"data"`
	Meta PageMeta       `json:"meta"`
}

// PageMeta defines model for PageMeta.
type PageMeta struct {
	Pagination Pagination `json:"pagination"`
	RequestId  string     `json:"request_id"`
	Timestamp  time.Time  `json:"timestamp"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	HasMore    bool    `json:"has_more"`
	Limit      int     `json:"limit"`
	NextCursor *string `json:"next_cursor"`
}

// PerformanceSummary defines model for PerformanceSummary.
type PerformanceSummary struct {
	AllTime  AllTimePerformance `json:"all_time"`
	ThisWeek PerformanceWindow  `json:"this_week"`
	Today    PerformanceWindow  `json:"today"`
}

// PerformanceWindow defines model for PerformanceWindow.
type PerformanceWindow struct {
	Bets        int     `json:"bets"`
	Losses      int     `json:"losses"`
	ProfitUnits float32 `json:"profit_units"`
	Wins        int     `json:"wins"`
}

// PipelineRunAcceptedData defines model for PipelineRunAcceptedData.
type PipelineRunAcceptedData struct {
	GamesQueued   int               `json:"games_queued"`
	League        *string           `json:"league"`
	PipelineRunId string            `json:"pipeline_run_id"`
	StartedAt     string            `json:"started_at"`
	Status        string            `json:"status"`
	Steps         map[string]string `json:"steps"`
}

// PipelineRunData defines model for PipelineRunData.
type PipelineRunData struct {
	BetsPlaced     int                    `json:"bets_placed"`
	EdgesFound     int                    `json:"edges_found"`
	Error          *string                `json:"error"`
	FinishedAt     *string                `json:"finished_at"`
	GamesProcessed int                    `json:"games_processed"`
	League         *string                `json:"league"`
	Params         map[string]interface{} `json:"params"`
	PipelineRunId  string                 `json:"pipeline_run_id"`
	StartedAt      string                 `json:"started_at"`
	Status         string                 `json:"status"`
	Steps          map[string]interface{} `json:"steps"`
	Trigger        string                 `json:"trigger"`
}

// PipelineRunRequest defines model for PipelineRunRequest.
type PipelineRunRequest struct {
	AutoBet          *bool                   `json:"auto_bet,omitempty"`
	ForceRefresh     *bool                   `json:"force_refresh,omitempty"`
	GameIds          *[]string               `json:"game_ids"`
	League           *string                 `json:"league"`
	SimulationConfig *map[string]interface{} `json:"simulation_config"`
}

// PipelineStatus defines model for PipelineStatus.
type PipelineStatus struct {
	LastRun          *LastRun `json:"last_run"`
	NextScheduledRun *string  `json:"next_scheduled_run"`
}

// ScheduleData defines model for ScheduleData.
type ScheduleData struct {
	AutoBet          bool                    `json:"auto_bet"`
	CronExpression   string                  `json:"cron_expression"`
	Description      *string                 `json:"description"`
	Enabled          bool                    `json:"enabled"`
	Id               string                  `json:"id"`
	LastRunAt        *string                 `json:"last_run_at"`
	League           string                  `json:"league"`
	MinEdgeThreshold float32                 `json:"min_edge_threshold"`
	NextRunAt        *string                 `json:"next_run_at"`
	SimulationConfig *map[string]interface{} `json:"simulation_config"`
	Timezone         string                  `json:"timezone"`
}

// ScheduleListData defines model for ScheduleListData.
type ScheduleListData struct {
	Schedules []ScheduleData `json:"schedules"`
}

// ScheduleRequest defines model for ScheduleRequest.
type ScheduleRequest struct {
	AutoBet          *bool                   `json:"auto_bet,omitempty"`
	CronExpression   string                  `json:"cron_expression"`
	Description      *string                 `json:"description"`
	Enabled          *bool                   `json:"enabled,omitempty"`
	League           string                  `json:"league"`
	MinEdgeThreshold *float32                `json:"min_edge_threshold,omitempty"`
	SimulationConfig *map[string]interface{} `json:"simulation_config"`
	Timezone         *string                 `json:"timezone,omitempty"`
}

// SlateData defines model for SlateData.
type SlateData struct {
	Date  string      `json:"date"`
	Games []SlateGame `json:"games"`
}

// SlateEdge defines model for SlateEdge.
type SlateEdge struct {
	EdgePercentage float32 `json:"edge_percentage"`
	HasPaperBet    bool    `json:"has_paper_bet"`
	Id             string  `json:"id"`
	MarketType     string  `json:"market_type"`
	Selection      string  `json:"selection"`
	SportsbookKey  string  `json:"sportsbook_key"`
}

// SlateGame defines model for SlateGame.
type SlateGame struct {
	AwayTeam       SlateTeam        `json:"away_team"`
	Edges          []SlateEdge      `json:"edges"`
	GameId         string           `json:"game_id"`
	HomeTeam       SlateTeam        `json:"home_team"`
	League         string           `json:"league"`
	Prediction     *SlatePrediction `json:"prediction"`
	ScheduledStart string           `json:"scheduled_start"`
	Status         string           `json:"status"`
}

// SlatePrediction defines model for SlatePrediction.
type SlatePrediction struct {
	Id                   string  `json:"id"`
	MarketType           string  `json:"market_type"`
	PredictedAt          string  `json:"predicted_at"`
	PredictedProbability float32 `json:"predicted_probability"`
	Selection            string  `json:"selection"`
}

// SlateTeam defines model for SlateTeam.
type SlateTeam struct {
	Abbreviation string `json:"abbreviation"`
	Id           string `json:"id"`
	Name         string `json:"name"`
}

// TopEdge defines model for TopEdge.
type TopEdge struct {
	EdgePercentage float32 `json:"edge_percentage"`
	Id             string  `json:"id"`
	Selection      string  `json:"selection"`
	SportsbookKey  string  `json:"sportsbook_key"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input *interface{}               `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// ListAlertsApiV1AgentAlertsGetParams defines parameters for ListAlertsApiV1AgentAlertsGet.
type ListAlertsApiV1AgentAlertsGetParams struct {
	// Priority Filter by priority: LOW, MEDIUM, HIGH.
	Priority *string `form:"priority,omitempty" json:"priority,omitempty"`

	// Acknowledged Filter by acknowledgement state.
	Acknowledged *bool `form:"acknowledged,omitempty" json:"acknowledged,omitempty"`

	// Limit Max results per page.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetDashboardApiV1AgentDashboardGetParams defines parameters for GetDashboardApiV1AgentDashboardGet.
type GetDashboardApiV1AgentDashboardGetParams struct {
	// League Filter by league; comma-separated for multiple.
	League *string `form:"league,omitempty" json:"league,omitempty"`
}

// ListEdgesApiV1AgentEdgesGetParams defines parameters for ListEdgesApiV1AgentEdgesGet.
type ListEdgesApiV1AgentEdgesGetParams struct {
	// League Filter by league; comma-separated for multiple.
	League *string `form:"league,omitempty" json:"league,omitempty"`

	// Date Filter by game date (ISO 8601 date).
	Date *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`

	// MinEdge Minimum edge percentage to include.
	MinEdge *float32 `form:"min_edge,omitempty" json:"min_edge,omitempty"`

	// MarketType Filter by market type.
	MarketType *string `form:"market_type,omitempty" json:"market_type,omitempty"`

	// IsStale Include stale edges (default: only fresh edges).
	IsStale *bool `form:"is_stale,omitempty" json:"is_stale,omitempty"`

	// Limit Max results per page.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetSlateApiV1AgentSlateGetParams defines parameters for GetSlateApiV1AgentSlateGet.
type GetSlateApiV1AgentSlateGetParams struct {
	// League Filter by league; comma-separated for multiple.
	League *string `form:"league,omitempty" json:"league,omitempty"`

	// Date Game date (ISO 8601 date); defaults to today.
	Date *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
}

// CreateAnalysisApiV1AgentAnalysisPostJSONRequestBody defines body for CreateAnalysisApiV1AgentAnalysisPost for application/json ContentType.
type CreateAnalysisApiV1AgentAnalysisPostJSONRequestBody = AnalysisRequest

// RunPipelineApiV1AgentPipelineRunPostJSONRequestBody defines body for RunPipelineApiV1AgentPipelineRunPost for application/json ContentType.
type RunPipelineApiV1AgentPipelineRunPostJSONRequestBody = PipelineRunRequest

// UpsertScheduleApiV1AgentSchedulePostJSONRequestBody defines body for UpsertScheduleApiV1AgentSchedulePost for application/json ContentType.
type UpsertScheduleApiV1AgentSchedulePostJSONRequestBody = ScheduleRequest

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListAlertsApiV1AgentAlertsGet request
	ListAlertsApiV1AgentAlertsGet(ctx context.Context, params *ListAlertsApiV1AgentAlertsGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePut request
	AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePut(ctx context.Context, alertId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateAnalysisApiV1AgentAnalysisPostWithBody request with any body
	CreateAnalysisApiV1AgentAnalysisPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateAnalysisApiV1AgentAnalysisPost(ctx context.Context, body CreateAnalysisApiV1AgentAnalysisPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAnalysisApiV1AgentAnalysisAnalysisIdGet request
	GetAnalysisApiV1AgentAnalysisAnalysisIdGet(ctx context.Context, analysisId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDashboardApiV1AgentDashboardGet request
	GetDashboardApiV1AgentDashboardGet(ctx context.Context, params *GetDashboardApiV1AgentDashboardGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListEdgesApiV1AgentEdgesGet request
	ListEdgesApiV1AgentEdgesGet(ctx context.Context, params *ListEdgesApiV1AgentEdgesGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEdgeApiV1AgentEdgesEdgeIdGet request
	GetEdgeApiV1AgentEdgesEdgeIdGet(ctx context.Context, edgeId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealthApiV1AgentHealthGet request
	GetHealthApiV1AgentHealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RunPipelineApiV1AgentPipelineRunPostWithBody request with any body
	RunPipelineApiV1AgentPipelineRunPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RunPipelineApiV1AgentPipelineRunPost(ctx context.Context, body RunPipelineApiV1AgentPipelineRunPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGet request
	GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGet(ctx context.Context, pipelineRunId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListSchedulesApiV1AgentScheduleGet request
	ListSchedulesApiV1AgentScheduleGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpsertScheduleApiV1AgentSchedulePostWithBody request with any body
	UpsertScheduleApiV1AgentSchedulePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpsertScheduleApiV1AgentSchedulePost(ctx context.Context, body UpsertScheduleApiV1AgentSchedulePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSlateApiV1AgentSlateGet request
	GetSlateApiV1AgentSlateGet(ctx context.Context, params *GetSlateApiV1AgentSlateGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListAlertsApiV1AgentAlertsGet(ctx context.Context, params *ListAlertsApiV1AgentAlertsGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAlertsApiV1AgentAlertsGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePut(ctx context.Context, alertId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutRequest(c.Server, alertId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAnalysisApiV1AgentAnalysisPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAnalysisApiV1AgentAnalysisPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAnalysisApiV1AgentAnalysisPost(ctx context.Context, body CreateAnalysisApiV1AgentAnalysisPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAnalysisApiV1AgentAnalysisPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAnalysisApiV1AgentAnalysisAnalysisIdGet(ctx context.Context, analysisId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAnalysisApiV1AgentAnalysisAnalysisIdGetRequest(c.Server, analysisId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDashboardApiV1AgentDashboardGet(ctx context.Context, params *GetDashboardApiV1AgentDashboardGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDashboardApiV1AgentDashboardGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListEdgesApiV1AgentEdgesGet(ctx context.Context, params *ListEdgesApiV1AgentEdgesGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListEdgesApiV1AgentEdgesGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetEdgeApiV1AgentEdgesEdgeIdGet(ctx context.Context, edgeId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEdgeApiV1AgentEdgesEdgeIdGetRequest(c.Server, edgeId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealthApiV1AgentHealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthApiV1AgentHealthGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RunPipelineApiV1AgentPipelineRunPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRunPipelineApiV1AgentPipelineRunPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RunPipelineApiV1AgentPipelineRunPost(ctx context.Context, body RunPipelineApiV1AgentPipelineRunPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRunPipelineApiV1AgentPipelineRunPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGet(ctx context.Context, pipelineRunId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetRequest(c.Server, pipelineRunId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListSchedulesApiV1AgentScheduleGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSchedulesApiV1AgentScheduleGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpsertScheduleApiV1AgentSchedulePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertScheduleApiV1AgentSchedulePostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpsertScheduleApiV1AgentSchedulePost(ctx context.Context, body UpsertScheduleApiV1AgentSchedulePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertScheduleApiV1AgentSchedulePostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSlateApiV1AgentSlateGet(ctx context.Context, params *GetSlateApiV1AgentSlateGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSlateApiV1AgentSlateGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListAlertsApiV1AgentAlertsGetRequest generates requests for ListAlertsApiV1AgentAlertsGet
func NewListAlertsApiV1AgentAlertsGetRequest(server string, params *ListAlertsApiV1AgentAlertsGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/agent/alerts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Priority != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "priority", runtime.ParamLocationQuery, *params.Priority); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Acknowledged != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "acknowledged", runtime.ParamLocationQuery, *params.Acknowledged); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutRequest generates requests for AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePut
func NewAcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutRequest(server string, alertId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "alert_id", runtime.ParamLocationPath, alertId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/agent/alerts/%s/acknowledge", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateAnalysisApiV1AgentAnalysisPostRequest calls the generic CreateAnalysisApiV1AgentAnalysisPost builder with application/json body
func NewCreateAnalysisApiV1AgentAnalysisPostRequest(server string, body CreateAnalysisApiV1AgentAnalysisPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateAnalysisApiV1AgentAnalysisPostRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateAnalysisApiV1AgentAnalysisPostRequestWithBody generates requests for CreateAnalysisApiV1AgentAnalysisPost with any type of body
func NewCreateAnalysisApiV1AgentAnalysisPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/agent/analysis")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetAnalysisApiV1AgentAnalysisAnalysisIdGetRequest generates requests for GetAnalysisApiV1AgentAnalysisAnalysisIdGet
func NewGetAnalysisApiV1AgentAnalysisAnalysisIdGetRequest(server string, analysisId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "analysis_id", runtime.ParamLocationPath, analysisId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/agent/analysis/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDashboardApiV1AgentDashboardGetRequest generates requests for GetDashboardApiV1AgentDashboardGet
func NewGetDashboardApiV1AgentDashboardGetRequest(server string, params *GetDashboardApiV1AgentDashboardGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/agent/dashboard")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.League != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "league", runtime.ParamLocationQuery, *params.League); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListEdgesApiV1AgentEdgesGetRequest generates requests for ListEdgesApiV1AgentEdgesGet
func NewListEdgesApiV1AgentEdgesGetRequest(server string, params *ListEdgesApiV1AgentEdgesGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/agent/edges")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.League != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "league", runtime.ParamLocationQuery, *params.League); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Date != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "date", runtime.ParamLocationQuery, *params.Date); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MinEdge != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "min_edge", runtime.ParamLocationQuery, *params.MinEdge); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MarketType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "market_type", runtime.ParamLocationQuery, *params.MarketType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.IsStale != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "is_stale", runtime.ParamLocationQuery, *params.IsStale); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetEdgeApiV1AgentEdgesEdgeIdGetRequest generates requests for GetEdgeApiV1AgentEdgesEdgeIdGet
func NewGetEdgeApiV1AgentEdgesEdgeIdGetRequest(server string, edgeId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "edge_id", runtime.ParamLocationPath, edgeId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/agent/edges/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthApiV1AgentHealthGetRequest generates requests for GetHealthApiV1AgentHealthGet
func NewGetHealthApiV1AgentHealthGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/agent/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRunPipelineApiV1AgentPipelineRunPostRequest calls the generic RunPipelineApiV1AgentPipelineRunPost builder with application/json body
func NewRunPipelineApiV1AgentPipelineRunPostRequest(server string, body RunPipelineApiV1AgentPipelineRunPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRunPipelineApiV1AgentPipelineRunPostRequestWithBody(server, "application/json", bodyReader)
}

// NewRunPipelineApiV1AgentPipelineRunPostRequestWithBody generates requests for RunPipelineApiV1AgentPipelineRunPost with any type of body
func NewRunPipelineApiV1AgentPipelineRunPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/agent/pipeline/run")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetRequest generates requests for GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGet
func NewGetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetRequest(server string, pipelineRunId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "pipeline_run_id", runtime.ParamLocationPath, pipelineRunId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/agent/pipeline/runs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListSchedulesApiV1AgentScheduleGetRequest generates requests for ListSchedulesApiV1AgentScheduleGet
func NewListSchedulesApiV1AgentScheduleGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/agent/schedule")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpsertScheduleApiV1AgentSchedulePostRequest calls the generic UpsertScheduleApiV1AgentSchedulePost builder with application/json body
func NewUpsertScheduleApiV1AgentSchedulePostRequest(server string, body UpsertScheduleApiV1AgentSchedulePostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpsertScheduleApiV1AgentSchedulePostRequestWithBody(server, "application/json", bodyReader)
}

// NewUpsertScheduleApiV1AgentSchedulePostRequestWithBody generates requests for UpsertScheduleApiV1AgentSchedulePost with any type of body
func NewUpsertScheduleApiV1AgentSchedulePostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/agent/schedule")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetSlateApiV1AgentSlateGetRequest generates requests for GetSlateApiV1AgentSlateGet
func NewGetSlateApiV1AgentSlateGetRequest(server string, params *GetSlateApiV1AgentSlateGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/agent/slate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.League != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "league", runtime.ParamLocationQuery, *params.League); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Date != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "date", runtime.ParamLocationQuery, *params.Date); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListAlertsApiV1AgentAlertsGetWithResponse request
	ListAlertsApiV1AgentAlertsGetWithResponse(ctx context.Context, params *ListAlertsApiV1AgentAlertsGetParams, reqEditors ...RequestEditorFn) (*ListAlertsApiV1AgentAlertsGetResponse, error)

	// AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutWithResponse request
	AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutWithResponse(ctx context.Context, alertId openapi_types.UUID, reqEditors ...RequestEditorFn) (*AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutResponse, error)

	// CreateAnalysisApiV1AgentAnalysisPostWithBodyWithResponse request with any body
	CreateAnalysisApiV1AgentAnalysisPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAnalysisApiV1AgentAnalysisPostResponse, error)

	CreateAnalysisApiV1AgentAnalysisPostWithResponse(ctx context.Context, body CreateAnalysisApiV1AgentAnalysisPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAnalysisApiV1AgentAnalysisPostResponse, error)

	// GetAnalysisApiV1AgentAnalysisAnalysisIdGetWithResponse request
	GetAnalysisApiV1AgentAnalysisAnalysisIdGetWithResponse(ctx context.Context, analysisId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetAnalysisApiV1AgentAnalysisAnalysisIdGetResponse, error)

	// GetDashboardApiV1AgentDashboardGetWithResponse request
	GetDashboardApiV1AgentDashboardGetWithResponse(ctx context.Context, params *GetDashboardApiV1AgentDashboardGetParams, reqEditors ...RequestEditorFn) (*GetDashboardApiV1AgentDashboardGetResponse, error)

	// ListEdgesApiV1AgentEdgesGetWithResponse request
	ListEdgesApiV1AgentEdgesGetWithResponse(ctx context.Context, params *ListEdgesApiV1AgentEdgesGetParams, reqEditors ...RequestEditorFn) (*ListEdgesApiV1AgentEdgesGetResponse, error)

	// GetEdgeApiV1AgentEdgesEdgeIdGetWithResponse request
	GetEdgeApiV1AgentEdgesEdgeIdGetWithResponse(ctx context.Context, edgeId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetEdgeApiV1AgentEdgesEdgeIdGetResponse, error)

	// GetHealthApiV1AgentHealthGetWithResponse request
	GetHealthApiV1AgentHealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthApiV1AgentHealthGetResponse, error)

	// RunPipelineApiV1AgentPipelineRunPostWithBodyWithResponse request with any body
	RunPipelineApiV1AgentPipelineRunPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RunPipelineApiV1AgentPipelineRunPostResponse, error)

	RunPipelineApiV1AgentPipelineRunPostWithResponse(ctx context.Context, body RunPipelineApiV1AgentPipelineRunPostJSONRequestBody, reqEditors ...RequestEditorFn) (*RunPipelineApiV1AgentPipelineRunPostResponse, error)

	// GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetWithResponse request
	GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetWithResponse(ctx context.Context, pipelineRunId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetResponse, error)

	// ListSchedulesApiV1AgentScheduleGetWithResponse request
	ListSchedulesApiV1AgentScheduleGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSchedulesApiV1AgentScheduleGetResponse, error)

	// UpsertScheduleApiV1AgentSchedulePostWithBodyWithResponse request with any body
	UpsertScheduleApiV1AgentSchedulePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertScheduleApiV1AgentSchedulePostResponse, error)

	UpsertScheduleApiV1AgentSchedulePostWithResponse(ctx context.Context, body UpsertScheduleApiV1AgentSchedulePostJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertScheduleApiV1AgentSchedulePostResponse, error)

	// GetSlateApiV1AgentSlateGetWithResponse request
	GetSlateApiV1AgentSlateGetWithResponse(ctx context.Context, params *GetSlateApiV1AgentSlateGetParams, reqEditors ...RequestEditorFn) (*GetSlateApiV1AgentSlateGetResponse, error)
}

type ListAlertsApiV1AgentAlertsGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PageEnvelopeAlertData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r ListAlertsApiV1AgentAlertsGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAlertsApiV1AgentAlertsGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeAlertData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateAnalysisApiV1AgentAnalysisPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeAnalysisData
	JSON201      *EnvelopeAnalysisData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r CreateAnalysisApiV1AgentAnalysisPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateAnalysisApiV1AgentAnalysisPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAnalysisApiV1AgentAnalysisAnalysisIdGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeAnalysisData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetAnalysisApiV1AgentAnalysisAnalysisIdGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAnalysisApiV1AgentAnalysisAnalysisIdGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDashboardApiV1AgentDashboardGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeDashboardData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetDashboardApiV1AgentDashboardGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDashboardApiV1AgentDashboardGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListEdgesApiV1AgentEdgesGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PageEnvelopeEdgeListItem
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r ListEdgesApiV1AgentEdgesGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListEdgesApiV1AgentEdgesGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetEdgeApiV1AgentEdgesEdgeIdGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeEdgeDetailData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetEdgeApiV1AgentEdgesEdgeIdGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEdgeApiV1AgentEdgesEdgeIdGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthApiV1AgentHealthGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeHealthData
}

// Status returns HTTPResponse.Status
func (r GetHealthApiV1AgentHealthGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthApiV1AgentHealthGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RunPipelineApiV1AgentPipelineRunPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *EnvelopePipelineRunAcceptedData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r RunPipelineApiV1AgentPipelineRunPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RunPipelineApiV1AgentPipelineRunPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopePipelineRunData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListSchedulesApiV1AgentScheduleGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeScheduleListData
}

// Status returns HTTPResponse.Status
func (r ListSchedulesApiV1AgentScheduleGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSchedulesApiV1AgentScheduleGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpsertScheduleApiV1AgentSchedulePostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeScheduleData
	JSON201      *EnvelopeScheduleData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r UpsertScheduleApiV1AgentSchedulePostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpsertScheduleApiV1AgentSchedulePostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSlateApiV1AgentSlateGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeSlateData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetSlateApiV1AgentSlateGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSlateApiV1AgentSlateGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListAlertsApiV1AgentAlertsGetWithResponse request returning *ListAlertsApiV1AgentAlertsGetResponse
func (c *ClientWithResponses) ListAlertsApiV1AgentAlertsGetWithResponse(ctx context.Context, params *ListAlertsApiV1AgentAlertsGetParams, reqEditors ...RequestEditorFn) (*ListAlertsApiV1AgentAlertsGetResponse, error) {
	rsp, err := c.ListAlertsApiV1AgentAlertsGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAlertsApiV1AgentAlertsGetResponse(rsp)
}

// AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutWithResponse request returning *AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutResponse
func (c *ClientWithResponses) AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutWithResponse(ctx context.Context, alertId openapi_types.UUID, reqEditors ...RequestEditorFn) (*AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutResponse, error) {
	rsp, err := c.AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePut(ctx, alertId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutResponse(rsp)
}

// CreateAnalysisApiV1AgentAnalysisPostWithBodyWithResponse request with arbitrary body returning *CreateAnalysisApiV1AgentAnalysisPostResponse
func (c *ClientWithResponses) CreateAnalysisApiV1AgentAnalysisPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAnalysisApiV1AgentAnalysisPostResponse, error) {
	rsp, err := c.CreateAnalysisApiV1AgentAnalysisPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAnalysisApiV1AgentAnalysisPostResponse(rsp)
}

func (c *ClientWithResponses) CreateAnalysisApiV1AgentAnalysisPostWithResponse(ctx context.Context, body CreateAnalysisApiV1AgentAnalysisPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAnalysisApiV1AgentAnalysisPostResponse, error) {
	rsp, err := c.CreateAnalysisApiV1AgentAnalysisPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAnalysisApiV1AgentAnalysisPostResponse(rsp)
}

// GetAnalysisApiV1AgentAnalysisAnalysisIdGetWithResponse request returning *GetAnalysisApiV1AgentAnalysisAnalysisIdGetResponse
func (c *ClientWithResponses) GetAnalysisApiV1AgentAnalysisAnalysisIdGetWithResponse(ctx context.Context, analysisId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetAnalysisApiV1AgentAnalysisAnalysisIdGetResponse, error) {
	rsp, err := c.GetAnalysisApiV1AgentAnalysisAnalysisIdGet(ctx, analysisId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAnalysisApiV1AgentAnalysisAnalysisIdGetResponse(rsp)
}

// GetDashboardApiV1AgentDashboardGetWithResponse request returning *GetDashboardApiV1AgentDashboardGetResponse
func (c *ClientWithResponses) GetDashboardApiV1AgentDashboardGetWithResponse(ctx context.Context, params *GetDashboardApiV1AgentDashboardGetParams, reqEditors ...RequestEditorFn) (*GetDashboardApiV1AgentDashboardGetResponse, error) {
	rsp, err := c.GetDashboardApiV1AgentDashboardGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDashboardApiV1AgentDashboardGetResponse(rsp)
}

// ListEdgesApiV1AgentEdgesGetWithResponse request returning *ListEdgesApiV1AgentEdgesGetResponse
func (c *ClientWithResponses) ListEdgesApiV1AgentEdgesGetWithResponse(ctx context.Context, params *ListEdgesApiV1AgentEdgesGetParams, reqEditors ...RequestEditorFn) (*ListEdgesApiV1AgentEdgesGetResponse, error) {
	rsp, err := c.ListEdgesApiV1AgentEdgesGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListEdgesApiV1AgentEdgesGetResponse(rsp)
}

// GetEdgeApiV1AgentEdgesEdgeIdGetWithResponse request returning *GetEdgeApiV1AgentEdgesEdgeIdGetResponse
func (c *ClientWithResponses) GetEdgeApiV1AgentEdgesEdgeIdGetWithResponse(ctx context.Context, edgeId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetEdgeApiV1AgentEdgesEdgeIdGetResponse, error) {
	rsp, err := c.GetEdgeApiV1AgentEdgesEdgeIdGet(ctx, edgeId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEdgeApiV1AgentEdgesEdgeIdGetResponse(rsp)
}

// GetHealthApiV1AgentHealthGetWithResponse request returning *GetHealthApiV1AgentHealthGetResponse
func (c *ClientWithResponses) GetHealthApiV1AgentHealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthApiV1AgentHealthGetResponse, error) {
	rsp, err := c.GetHealthApiV1AgentHealthGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthApiV1AgentHealthGetResponse(rsp)
}

// RunPipelineApiV1AgentPipelineRunPostWithBodyWithResponse request with arbitrary body returning *RunPipelineApiV1AgentPipelineRunPostResponse
func (c *ClientWithResponses) RunPipelineApiV1AgentPipelineRunPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RunPipelineApiV1AgentPipelineRunPostResponse, error) {
	rsp, err := c.RunPipelineApiV1AgentPipelineRunPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRunPipelineApiV1AgentPipelineRunPostResponse(rsp)
}

func (c *ClientWithResponses) RunPipelineApiV1AgentPipelineRunPostWithResponse(ctx context.Context, body RunPipelineApiV1AgentPipelineRunPostJSONRequestBody, reqEditors ...RequestEditorFn) (*RunPipelineApiV1AgentPipelineRunPostResponse, error) {
	rsp, err := c.RunPipelineApiV1AgentPipelineRunPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRunPipelineApiV1AgentPipelineRunPostResponse(rsp)
}

// GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetWithResponse request returning *GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetResponse
func (c *ClientWithResponses) GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetWithResponse(ctx context.Context, pipelineRunId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetResponse, error) {
	rsp, err := c.GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGet(ctx, pipelineRunId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetResponse(rsp)
}

// ListSchedulesApiV1AgentScheduleGetWithResponse request returning *ListSchedulesApiV1AgentScheduleGetResponse
func (c *ClientWithResponses) ListSchedulesApiV1AgentScheduleGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSchedulesApiV1AgentScheduleGetResponse, error) {
	rsp, err := c.ListSchedulesApiV1AgentScheduleGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSchedulesApiV1AgentScheduleGetResponse(rsp)
}

// UpsertScheduleApiV1AgentSchedulePostWithBodyWithResponse request with arbitrary body returning *UpsertScheduleApiV1AgentSchedulePostResponse
func (c *ClientWithResponses) UpsertScheduleApiV1AgentSchedulePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertScheduleApiV1AgentSchedulePostResponse, error) {
	rsp, err := c.UpsertScheduleApiV1AgentSchedulePostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertScheduleApiV1AgentSchedulePostResponse(rsp)
}

func (c *ClientWithResponses) UpsertScheduleApiV1AgentSchedulePostWithResponse(ctx context.Context, body UpsertScheduleApiV1AgentSchedulePostJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertScheduleApiV1AgentSchedulePostResponse, error) {
	rsp, err := c.UpsertScheduleApiV1AgentSchedulePost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertScheduleApiV1AgentSchedulePostResponse(rsp)
}

// GetSlateApiV1AgentSlateGetWithResponse request returning *GetSlateApiV1AgentSlateGetResponse
func (c *ClientWithResponses) GetSlateApiV1AgentSlateGetWithResponse(ctx context.Context, params *GetSlateApiV1AgentSlateGetParams, reqEditors ...RequestEditorFn) (*GetSlateApiV1AgentSlateGetResponse, error) {
	rsp, err := c.GetSlateApiV1AgentSlateGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSlateApiV1AgentSlateGetResponse(rsp)
}

// ParseListAlertsApiV1AgentAlertsGetResponse parses an HTTP response from a ListAlertsApiV1AgentAlertsGetWithResponse call
func ParseListAlertsApiV1AgentAlertsGetResponse(rsp *http.Response) (*ListAlertsApiV1AgentAlertsGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAlertsApiV1AgentAlertsGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PageEnvelopeAlertData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseAcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutResponse parses an HTTP response from a AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutWithResponse call
func ParseAcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutResponse(rsp *http.Response) (*AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AcknowledgeAlertApiV1AgentAlertsAlertIdAcknowledgePutResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeAlertData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseCreateAnalysisApiV1AgentAnalysisPostResponse parses an HTTP response from a CreateAnalysisApiV1AgentAnalysisPostWithResponse call
func ParseCreateAnalysisApiV1AgentAnalysisPostResponse(rsp *http.Response) (*CreateAnalysisApiV1AgentAnalysisPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateAnalysisApiV1AgentAnalysisPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeAnalysisData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest EnvelopeAnalysisData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetAnalysisApiV1AgentAnalysisAnalysisIdGetResponse parses an HTTP response from a GetAnalysisApiV1AgentAnalysisAnalysisIdGetWithResponse call
func ParseGetAnalysisApiV1AgentAnalysisAnalysisIdGetResponse(rsp *http.Response) (*GetAnalysisApiV1AgentAnalysisAnalysisIdGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAnalysisApiV1AgentAnalysisAnalysisIdGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeAnalysisData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetDashboardApiV1AgentDashboardGetResponse parses an HTTP response from a GetDashboardApiV1AgentDashboardGetWithResponse call
func ParseGetDashboardApiV1AgentDashboardGetResponse(rsp *http.Response) (*GetDashboardApiV1AgentDashboardGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDashboardApiV1AgentDashboardGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeDashboardData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseListEdgesApiV1AgentEdgesGetResponse parses an HTTP response from a ListEdgesApiV1AgentEdgesGetWithResponse call
func ParseListEdgesApiV1AgentEdgesGetResponse(rsp *http.Response) (*ListEdgesApiV1AgentEdgesGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListEdgesApiV1AgentEdgesGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PageEnvelopeEdgeListItem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetEdgeApiV1AgentEdgesEdgeIdGetResponse parses an HTTP response from a GetEdgeApiV1AgentEdgesEdgeIdGetWithResponse call
func ParseGetEdgeApiV1AgentEdgesEdgeIdGetResponse(rsp *http.Response) (*GetEdgeApiV1AgentEdgesEdgeIdGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEdgeApiV1AgentEdgesEdgeIdGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeEdgeDetailData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetHealthApiV1AgentHealthGetResponse parses an HTTP response from a GetHealthApiV1AgentHealthGetWithResponse call
func ParseGetHealthApiV1AgentHealthGetResponse(rsp *http.Response) (*GetHealthApiV1AgentHealthGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthApiV1AgentHealthGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeHealthData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRunPipelineApiV1AgentPipelineRunPostResponse parses an HTTP response from a RunPipelineApiV1AgentPipelineRunPostWithResponse call
func ParseRunPipelineApiV1AgentPipelineRunPostResponse(rsp *http.Response) (*RunPipelineApiV1AgentPipelineRunPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RunPipelineApiV1AgentPipelineRunPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest EnvelopePipelineRunAcceptedData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetResponse parses an HTTP response from a GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetWithResponse call
func ParseGetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetResponse(rsp *http.Response) (*GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPipelineRunApiV1AgentPipelineRunsPipelineRunIdGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopePipelineRunData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseListSchedulesApiV1AgentScheduleGetResponse parses an HTTP response from a ListSchedulesApiV1AgentScheduleGetWithResponse call
func ParseListSchedulesApiV1AgentScheduleGetResponse(rsp *http.Response) (*ListSchedulesApiV1AgentScheduleGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSchedulesApiV1AgentScheduleGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeScheduleListData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUpsertScheduleApiV1AgentSchedulePostResponse parses an HTTP response from a UpsertScheduleApiV1AgentSchedulePostWithResponse call
func ParseUpsertScheduleApiV1AgentSchedulePostResponse(rsp *http.Response) (*UpsertScheduleApiV1AgentSchedulePostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpsertScheduleApiV1AgentSchedulePostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeScheduleData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest EnvelopeScheduleData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetSlateApiV1AgentSlateGetResponse parses an HTTP response from a GetSlateApiV1AgentSlateGetWithResponse call
func ParseGetSlateApiV1AgentSlateGetResponse(rsp *http.Response) (*GetSlateApiV1AgentSlateGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSlateApiV1AgentSlateGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeSlateData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
