// Package predictionengine provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package predictionengine

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for PredictionRequestMarketTypes.
const (
	MONEYLINE PredictionRequestMarketTypes = "MONEYLINE"
	SPREAD    PredictionRequestMarketTypes = "SPREAD"
	TOTAL     PredictionRequestMarketTypes = "TOTAL"
)

// EdgeItem defines model for EdgeItem.
type EdgeItem struct {
	BestOddsAmerican     int     `json:"best_odds_american"`
	EdgePercentage       float32 `json:"edge_percentage"`
	ImpliedProbability   float32 `json:"implied_probability"`
	MarketType           string  `json:"market_type"`
	PredictedProbability float32 `json:"predicted_probability"`
	PredictionId         string  `json:"prediction_id"`
	Selection            string  `json:"selection"`
	SportsbookKey        string  `json:"sportsbook_key"`
}

// EdgesData defines model for EdgesData.
type EdgesData struct {
	Edges  []EdgeItem `json:"edges"`
	GameId string     `json:"game_id"`
}

// EnvelopeEdgesData defines model for Envelope_EdgesData_.
type EnvelopeEdgesData struct {
	Data EdgesData `json:"data"`
	Meta Meta      `json:"meta"`
}

// EnvelopeHealthData defines model for Envelope_HealthData_.
type EnvelopeHealthData struct {
	Data HealthData `json:"data"`
	Meta Meta       `json:"meta"`
}

// EnvelopeLatestPredictionsData defines model for Envelope_LatestPredictionsData_.
type EnvelopeLatestPredictionsData struct {
	Data LatestPredictionsData `json:"data"`
	Meta Meta                  `json:"meta"`
}

// EnvelopeModelVersionDetailData defines model for Envelope_ModelVersionDetailData_.
type EnvelopeModelVersionDetailData struct {
	Data ModelVersionDetailData `json:"data"`
	Meta Meta                   `json:"meta"`
}

// EnvelopePredictionDetailData defines model for Envelope_PredictionDetailData_.
type EnvelopePredictionDetailData struct {
	Data PredictionDetailData `json:"data"`
	Meta Meta                 `json:"meta"`
}

// EnvelopePredictionGroupData defines model for Envelope_PredictionGroupData_.
type EnvelopePredictionGroupData struct {
	Data PredictionGroupData `json:"data"`
	Meta Meta                `json:"meta"`
}

// EnvelopeRetrainData defines model for Envelope_RetrainData_.
type EnvelopeRetrainData struct {
	Data RetrainData `json:"data"`
	Meta Meta        `json:"meta"`
}

// EnvelopeListModelVersionData defines model for Envelope_list_ModelVersionData__.
type EnvelopeListModelVersionData struct {
	Data []ModelVersionData `json:"data"`
	Meta Meta               `json:"meta"`
}

// FeatureVectorData defines model for FeatureVectorData.
type FeatureVectorData struct {
	FeatureSourceVersions map[string]*string                                          `json:"feature_source_versions"`
	Features              map[string]*FeatureVectorData_Features_AdditionalProperties `json:"features"`
	Id                    string                                                      `json:"id"`
}

// FeatureVectorDataFeatures0 defines model for .
type FeatureVectorDataFeatures0 = float32

// FeatureVectorDataFeatures1 defines model for .
type FeatureVectorDataFeatures1 = int

// FeatureVectorDataFeatures2 defines model for .
type FeatureVectorDataFeatures2 = bool

// FeatureVectorData_Features_AdditionalProperties defines model for FeatureVectorData.features.AdditionalProperties.
type FeatureVectorData_Features_AdditionalProperties struct {
	union json.RawMessage
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// HealthData defines model for HealthData.
type HealthData struct {
	ActiveModels  map[string]string `json:"active_models"`
	Dependencies  map[string]string `json:"dependencies"`
	Service       *string           `json:"service,omitempty"`
	Status        string            `json:"status"`
	UptimeSeconds int               `json:"uptime_seconds"`
	Version       string            `json:"version"`
}

// LatestPredictionsData defines model for LatestPredictionsData.
type LatestPredictionsData struct {
	GameId      string           `json:"game_id"`
	Predictions []PredictionItem `json:"predictions"`
}

// Meta defines model for Meta.
type Meta struct {
	RequestId string    `json:"request_id"`
	Timestamp time.Time `json:"timestamp"`
}

// ModelVersionData defines model for ModelVersionData.
type ModelVersionData struct {
	Algorithm         string             `json:"algorithm"`
	EvaluationMetrics map[string]float32 `json:"evaluation_metrics"`
	Id                string             `json:"id"`
	IsActive          bool               `json:"is_active"`
	MarketType        string             `json:"market_type"`
	Notes             *string            `json:"notes"`
	Sport             string             `json:"sport"`
	TrainingDate      string             `json:"training_date"`
	TrainingSamples   int                `json:"training_samples"`
	VersionTag        string             `json:"version_tag"`
}

// ModelVersionDetailData defines model for ModelVersionDetailData.
type ModelVersionDetailData struct {
	Algorithm         string             `json:"algorithm"`
	EvaluationMetrics map[string]float32 `json:"evaluation_metrics"`
	FeatureNames      []string           `json:"feature_names"`
	Id                string             `json:"id"`
	IsActive          bool               `json:"is_active"`
	MarketType        string             `json:"market_type"`
	Notes             *string            `json:"notes"`
	Sport             string             `json:"sport"`
	TrainingDate      string             `json:"training_date"`
	TrainingSamples   int                `json:"training_samples"`
	VersionTag        string             `json:"version_tag"`
}

// PredictionDetailData defines model for PredictionDetailData.
type PredictionDetailData struct {
	AdjustmentMagnitude   float32            `json:"adjustment_magnitude"`
	ConfidenceLower       *float32           `json:"confidence_lower"`
	ConfidenceUpper       *float32           `json:"confidence_upper"`
	CreatedAt             string             `json:"created_at"`
	FeatureImportance     map[string]float32 `json:"feature_importance"`
	FeatureVector         FeatureVectorData  `json:"feature_vector"`
	GameId                string             `json:"game_id"`
	Id                    string             `json:"id"`
	MarketType            string             `json:"market_type"`
	ModelVersionId        string             `json:"model_version_id"`
	PredictedProbability  float32            `json:"predicted_probability"`
	Selection             string             `json:"selection"`
	SimulationProbability *float32           `json:"simulation_probability"`
}

// PredictionGroupData defines model for PredictionGroupData.
type PredictionGroupData struct {
	FeatureSourceVersions map[string]*string                                                `json:"feature_source_versions"`
	FeaturesUsed          map[string]*PredictionGroupData_FeaturesUsed_AdditionalProperties `json:"features_used"`
	GameId                string                                                            `json:"game_id"`
	Predictions           []PredictionItem                                                  `json:"predictions"`
	SimulationRunId       string                                                            `json:"simulation_run_id"`
}

// PredictionGroupDataFeaturesUsed0 defines model for .
type PredictionGroupDataFeaturesUsed0 = float32

// PredictionGroupDataFeaturesUsed1 defines model for .
type PredictionGroupDataFeaturesUsed1 = int

// PredictionGroupDataFeaturesUsed2 defines model for .
type PredictionGroupDataFeaturesUsed2 = bool

// PredictionGroupData_FeaturesUsed_AdditionalProperties defines model for PredictionGroupData.features_used.AdditionalProperties.
type PredictionGroupData_FeaturesUsed_AdditionalProperties struct {
	union json.RawMessage
}

// PredictionItem defines model for PredictionItem.
type PredictionItem struct {
	AdjustmentMagnitude   float32            `json:"adjustment_magnitude"`
	ConfidenceLower       *float32           `json:"confidence_lower"`
	ConfidenceUpper       *float32           `json:"confidence_upper"`
	CreatedAt             string             `json:"created_at"`
	FeatureImportance     map[string]float32 `json:"feature_importance"`
	Id                    string             `json:"id"`
	MarketType            string             `json:"market_type"`
	ModelVersionId        string             `json:"model_version_id"`
	PredictedProbability  float32            `json:"predicted_probability"`
	Selection             string             `json:"selection"`
	SimulationProbability *float32           `json:"simulation_probability"`
}

// PredictionRequest defines model for PredictionRequest.
type PredictionRequest struct {
	GameId          string                          `json:"game_id"`
	MarketTypes     *[]PredictionRequestMarketTypes `json:"market_types,omitempty"`
	SimulationRunId string                          `json:"simulation_run_id"`
}

// PredictionRequestMarketTypes defines model for PredictionRequest.MarketTypes.
type PredictionRequestMarketTypes string

// RetrainConfig defines model for RetrainConfig.
type RetrainConfig struct {
	DateFrom   *string  `json:"date_from"`
	DateTo     *string  `json:"date_to"`
	MinSamples *int     `json:"min_samples,omitempty"`
	TestSplit  *float32 `json:"test_split,omitempty"`
}

// RetrainData defines model for RetrainData.
type RetrainData struct {
	EstimatedDurationMinutes int    `json:"estimated_duration_minutes"`
	MarketType               string `json:"market_type"`
	RetrainId                string `json:"retrain_id"`
	Sport                    string `json:"sport"`
	StartedAt                string `json:"started_at"`
	Status                   string `json:"status"`
}

// RetrainRequest defines model for RetrainRequest.
type RetrainRequest struct {
	MarketType     string         `json:"market_type"`
	Sport          string         `json:"sport"`
	TrainingConfig *RetrainConfig `json:"training_config,omitempty"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input *interface{}               `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// EdgesForGameApiV1PredictGamesGameIdEdgesGetParams defines parameters for EdgesForGameApiV1PredictGamesGameIdEdgesGet.
type EdgesForGameApiV1PredictGamesGameIdEdgesGetParams struct {
	// MinEdge Minimum edge percentage to include.
	MinEdge *float32 `form:"min_edge,omitempty" json:"min_edge,omitempty"`

	// MarketType Filter by market type.
	MarketType *string `form:"market_type,omitempty" json:"market_type,omitempty"`
}

// LatestPredictionsApiV1PredictGamesGameIdLatestGetParams defines parameters for LatestPredictionsApiV1PredictGamesGameIdLatestGet.
type LatestPredictionsApiV1PredictGamesGameIdLatestGetParams struct {
	// MarketType Filter by market type; comma-separated for multiple.
	MarketType *string `form:"market_type,omitempty" json:"market_type,omitempty"`

	// ModelVersion Filter by a specific model version.
	ModelVersion *openapi_types.UUID `form:"model_version,omitempty" json:"model_version,omitempty"`
}

// ListModelsApiV1PredictModelsGetParams defines parameters for ListModelsApiV1PredictModelsGet.
type ListModelsApiV1PredictModelsGetParams struct {
	// Sport Filter by sport (e.g. BASKETBALL).
	Sport *string `form:"sport,omitempty" json:"sport,omitempty"`

	// MarketType Filter by market type.
	MarketType *string `form:"market_type,omitempty" json:"market_type,omitempty"`

	// IsActive Filter by active status.
	IsActive *bool `form:"is_active,omitempty" json:"is_active,omitempty"`
}

// CreatePredictionsApiV1PredictPredictionsPostParams defines parameters for CreatePredictionsApiV1PredictPredictionsPost.
type CreatePredictionsApiV1PredictPredictionsPostParams struct {
	// XIdempotencyKey UUID for idempotent submission (replayed for 24 hours).
	XIdempotencyKey *string `json:"x-idempotency-key,omitempty"`
}

// RetrainModelApiV1PredictModelsRetrainPostJSONRequestBody defines body for RetrainModelApiV1PredictModelsRetrainPost for application/json ContentType.
type RetrainModelApiV1PredictModelsRetrainPostJSONRequestBody = RetrainRequest

// CreatePredictionsApiV1PredictPredictionsPostJSONRequestBody defines body for CreatePredictionsApiV1PredictPredictionsPost for application/json ContentType.
type CreatePredictionsApiV1PredictPredictionsPostJSONRequestBody = PredictionRequest

// AsFeatureVectorDataFeatures0 returns the union data inside the FeatureVectorData_Features_AdditionalProperties as a FeatureVectorDataFeatures0
func (t FeatureVectorData_Features_AdditionalProperties) AsFeatureVectorDataFeatures0() (FeatureVectorDataFeatures0, error) {
	var body FeatureVectorDataFeatures0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFeatureVectorDataFeatures0 overwrites any union data inside the FeatureVectorData_Features_AdditionalProperties as the provided FeatureVectorDataFeatures0
func (t *FeatureVectorData_Features_AdditionalProperties) FromFeatureVectorDataFeatures0(v FeatureVectorDataFeatures0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFeatureVectorDataFeatures0 performs a merge with any union data inside the FeatureVectorData_Features_AdditionalProperties, using the provided FeatureVectorDataFeatures0
func (t *FeatureVectorData_Features_AdditionalProperties) MergeFeatureVectorDataFeatures0(v FeatureVectorDataFeatures0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFeatureVectorDataFeatures1 returns the union data inside the FeatureVectorData_Features_AdditionalProperties as a FeatureVectorDataFeatures1
func (t FeatureVectorData_Features_AdditionalProperties) AsFeatureVectorDataFeatures1() (FeatureVectorDataFeatures1, error) {
	var body FeatureVectorDataFeatures1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFeatureVectorDataFeatures1 overwrites any union data inside the FeatureVectorData_Features_AdditionalProperties as the provided FeatureVectorDataFeatures1
func (t *FeatureVectorData_Features_AdditionalProperties) FromFeatureVectorDataFeatures1(v FeatureVectorDataFeatures1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFeatureVectorDataFeatures1 performs a merge with any union data inside the FeatureVectorData_Features_AdditionalProperties, using the provided FeatureVectorDataFeatures1
func (t *FeatureVectorData_Features_AdditionalProperties) MergeFeatureVectorDataFeatures1(v FeatureVectorDataFeatures1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFeatureVectorDataFeatures2 returns the union data inside the FeatureVectorData_Features_AdditionalProperties as a FeatureVectorDataFeatures2
func (t FeatureVectorData_Features_AdditionalProperties) AsFeatureVectorDataFeatures2() (FeatureVectorDataFeatures2, error) {
	var body FeatureVectorDataFeatures2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFeatureVectorDataFeatures2 overwrites any union data inside the FeatureVectorData_Features_AdditionalProperties as the provided FeatureVectorDataFeatures2
func (t *FeatureVectorData_Features_AdditionalProperties) FromFeatureVectorDataFeatures2(v FeatureVectorDataFeatures2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFeatureVectorDataFeatures2 performs a merge with any union data inside the FeatureVectorData_Features_AdditionalProperties, using the provided FeatureVectorDataFeatures2
func (t *FeatureVectorData_Features_AdditionalProperties) MergeFeatureVectorDataFeatures2(v FeatureVectorDataFeatures2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FeatureVectorData_Features_AdditionalProperties) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *FeatureVectorData_Features_AdditionalProperties) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPredictionGroupDataFeaturesUsed0 returns the union data inside the PredictionGroupData_FeaturesUsed_AdditionalProperties as a PredictionGroupDataFeaturesUsed0
func (t PredictionGroupData_FeaturesUsed_AdditionalProperties) AsPredictionGroupDataFeaturesUsed0() (PredictionGroupDataFeaturesUsed0, error) {
	var body PredictionGroupDataFeaturesUsed0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPredictionGroupDataFeaturesUsed0 overwrites any union data inside the PredictionGroupData_FeaturesUsed_AdditionalProperties as the provided PredictionGroupDataFeaturesUsed0
func (t *PredictionGroupData_FeaturesUsed_AdditionalProperties) FromPredictionGroupDataFeaturesUsed0(v PredictionGroupDataFeaturesUsed0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePredictionGroupDataFeaturesUsed0 performs a merge with any union data inside the PredictionGroupData_FeaturesUsed_AdditionalProperties, using the provided PredictionGroupDataFeaturesUsed0
func (t *PredictionGroupData_FeaturesUsed_AdditionalProperties) MergePredictionGroupDataFeaturesUsed0(v PredictionGroupDataFeaturesUsed0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPredictionGroupDataFeaturesUsed1 returns the union data inside the PredictionGroupData_FeaturesUsed_AdditionalProperties as a PredictionGroupDataFeaturesUsed1
func (t PredictionGroupData_FeaturesUsed_AdditionalProperties) AsPredictionGroupDataFeaturesUsed1() (PredictionGroupDataFeaturesUsed1, error) {
	var body PredictionGroupDataFeaturesUsed1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPredictionGroupDataFeaturesUsed1 overwrites any union data inside the PredictionGroupData_FeaturesUsed_AdditionalProperties as the provided PredictionGroupDataFeaturesUsed1
func (t *PredictionGroupData_FeaturesUsed_AdditionalProperties) FromPredictionGroupDataFeaturesUsed1(v PredictionGroupDataFeaturesUsed1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePredictionGroupDataFeaturesUsed1 performs a merge with any union data inside the PredictionGroupData_FeaturesUsed_AdditionalProperties, using the provided PredictionGroupDataFeaturesUsed1
func (t *PredictionGroupData_FeaturesUsed_AdditionalProperties) MergePredictionGroupDataFeaturesUsed1(v PredictionGroupDataFeaturesUsed1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPredictionGroupDataFeaturesUsed2 returns the union data inside the PredictionGroupData_FeaturesUsed_AdditionalProperties as a PredictionGroupDataFeaturesUsed2
func (t PredictionGroupData_FeaturesUsed_AdditionalProperties) AsPredictionGroupDataFeaturesUsed2() (PredictionGroupDataFeaturesUsed2, error) {
	var body PredictionGroupDataFeaturesUsed2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPredictionGroupDataFeaturesUsed2 overwrites any union data inside the PredictionGroupData_FeaturesUsed_AdditionalProperties as the provided PredictionGroupDataFeaturesUsed2
func (t *PredictionGroupData_FeaturesUsed_AdditionalProperties) FromPredictionGroupDataFeaturesUsed2(v PredictionGroupDataFeaturesUsed2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePredictionGroupDataFeaturesUsed2 performs a merge with any union data inside the PredictionGroupData_FeaturesUsed_AdditionalProperties, using the provided PredictionGroupDataFeaturesUsed2
func (t *PredictionGroupData_FeaturesUsed_AdditionalProperties) MergePredictionGroupDataFeaturesUsed2(v PredictionGroupDataFeaturesUsed2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PredictionGroupData_FeaturesUsed_AdditionalProperties) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PredictionGroupData_FeaturesUsed_AdditionalProperties) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// EdgesForGameApiV1PredictGamesGameIdEdgesGet request
	EdgesForGameApiV1PredictGamesGameIdEdgesGet(ctx context.Context, gameId string, params *EdgesForGameApiV1PredictGamesGameIdEdgesGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LatestPredictionsApiV1PredictGamesGameIdLatestGet request
	LatestPredictionsApiV1PredictGamesGameIdLatestGet(ctx context.Context, gameId string, params *LatestPredictionsApiV1PredictGamesGameIdLatestGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealthApiV1PredictHealthGet request
	GetHealthApiV1PredictHealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListModelsApiV1PredictModelsGet request
	ListModelsApiV1PredictModelsGet(ctx context.Context, params *ListModelsApiV1PredictModelsGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RetrainModelApiV1PredictModelsRetrainPostWithBody request with any body
	RetrainModelApiV1PredictModelsRetrainPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RetrainModelApiV1PredictModelsRetrainPost(ctx context.Context, body RetrainModelApiV1PredictModelsRetrainPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetModelApiV1PredictModelsModelIdGet request
	GetModelApiV1PredictModelsModelIdGet(ctx context.Context, modelId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePredictionsApiV1PredictPredictionsPostWithBody request with any body
	CreatePredictionsApiV1PredictPredictionsPostWithBody(ctx context.Context, params *CreatePredictionsApiV1PredictPredictionsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreatePredictionsApiV1PredictPredictionsPost(ctx context.Context, params *CreatePredictionsApiV1PredictPredictionsPostParams, body CreatePredictionsApiV1PredictPredictionsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPredictionApiV1PredictPredictionsPredictionIdGet request
	GetPredictionApiV1PredictPredictionsPredictionIdGet(ctx context.Context, predictionId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) EdgesForGameApiV1PredictGamesGameIdEdgesGet(ctx context.Context, gameId string, params *EdgesForGameApiV1PredictGamesGameIdEdgesGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEdgesForGameApiV1PredictGamesGameIdEdgesGetRequest(c.Server, gameId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LatestPredictionsApiV1PredictGamesGameIdLatestGet(ctx context.Context, gameId string, params *LatestPredictionsApiV1PredictGamesGameIdLatestGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLatestPredictionsApiV1PredictGamesGameIdLatestGetRequest(c.Server, gameId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealthApiV1PredictHealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthApiV1PredictHealthGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListModelsApiV1PredictModelsGet(ctx context.Context, params *ListModelsApiV1PredictModelsGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListModelsApiV1PredictModelsGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RetrainModelApiV1PredictModelsRetrainPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRetrainModelApiV1PredictModelsRetrainPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RetrainModelApiV1PredictModelsRetrainPost(ctx context.Context, body RetrainModelApiV1PredictModelsRetrainPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRetrainModelApiV1PredictModelsRetrainPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetModelApiV1PredictModelsModelIdGet(ctx context.Context, modelId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetModelApiV1PredictModelsModelIdGetRequest(c.Server, modelId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePredictionsApiV1PredictPredictionsPostWithBody(ctx context.Context, params *CreatePredictionsApiV1PredictPredictionsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePredictionsApiV1PredictPredictionsPostRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePredictionsApiV1PredictPredictionsPost(ctx context.Context, params *CreatePredictionsApiV1PredictPredictionsPostParams, body CreatePredictionsApiV1PredictPredictionsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePredictionsApiV1PredictPredictionsPostRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPredictionApiV1PredictPredictionsPredictionIdGet(ctx context.Context, predictionId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPredictionApiV1PredictPredictionsPredictionIdGetRequest(c.Server, predictionId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewEdgesForGameApiV1PredictGamesGameIdEdgesGetRequest generates requests for EdgesForGameApiV1PredictGamesGameIdEdgesGet
func NewEdgesForGameApiV1PredictGamesGameIdEdgesGetRequest(server string, gameId string, params *EdgesForGameApiV1PredictGamesGameIdEdgesGetParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "game_id", runtime.ParamLocationPath, gameId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/predict/games/%s/edges", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.MinEdge != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "min_edge", runtime.ParamLocationQuery, *params.MinEdge); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MarketType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "market_type", runtime.ParamLocationQuery, *params.MarketType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLatestPredictionsApiV1PredictGamesGameIdLatestGetRequest generates requests for LatestPredictionsApiV1PredictGamesGameIdLatestGet
func NewLatestPredictionsApiV1PredictGamesGameIdLatestGetRequest(server string, gameId string, params *LatestPredictionsApiV1PredictGamesGameIdLatestGetParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "game_id", runtime.ParamLocationPath, gameId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/predict/games/%s/latest", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.MarketType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "market_type", runtime.ParamLocationQuery, *params.MarketType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ModelVersion != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "model_version", runtime.ParamLocationQuery, *params.ModelVersion); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthApiV1PredictHealthGetRequest generates requests for GetHealthApiV1PredictHealthGet
func NewGetHealthApiV1PredictHealthGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/predict/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListModelsApiV1PredictModelsGetRequest generates requests for ListModelsApiV1PredictModelsGet
func NewListModelsApiV1PredictModelsGetRequest(server string, params *ListModelsApiV1PredictModelsGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/predict/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Sport != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sport", runtime.ParamLocationQuery, *params.Sport); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MarketType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "market_type", runtime.ParamLocationQuery, *params.MarketType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.IsActive != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "is_active", runtime.ParamLocationQuery, *params.IsActive); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRetrainModelApiV1PredictModelsRetrainPostRequest calls the generic RetrainModelApiV1PredictModelsRetrainPost builder with application/json body
func NewRetrainModelApiV1PredictModelsRetrainPostRequest(server string, body RetrainModelApiV1PredictModelsRetrainPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRetrainModelApiV1PredictModelsRetrainPostRequestWithBody(server, "application/json", bodyReader)
}

// NewRetrainModelApiV1PredictModelsRetrainPostRequestWithBody generates requests for RetrainModelApiV1PredictModelsRetrainPost with any type of body
func NewRetrainModelApiV1PredictModelsRetrainPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/predict/models/retrain")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetModelApiV1PredictModelsModelIdGetRequest generates requests for GetModelApiV1PredictModelsModelIdGet
func NewGetModelApiV1PredictModelsModelIdGetRequest(server string, modelId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "model_id", runtime.ParamLocationPath, modelId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/predict/models/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreatePredictionsApiV1PredictPredictionsPostRequest calls the generic CreatePredictionsApiV1PredictPredictionsPost builder with application/json body
func NewCreatePredictionsApiV1PredictPredictionsPostRequest(server string, params *CreatePredictionsApiV1PredictPredictionsPostParams, body CreatePredictionsApiV1PredictPredictionsPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePredictionsApiV1PredictPredictionsPostRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreatePredictionsApiV1PredictPredictionsPostRequestWithBody generates requests for CreatePredictionsApiV1PredictPredictionsPost with any type of body
func NewCreatePredictionsApiV1PredictPredictionsPostRequestWithBody(server string, params *CreatePredictionsApiV1PredictPredictionsPostParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/predict/predictions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XIdempotencyKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "x-idempotency-key", runtime.ParamLocationHeader, *params.XIdempotencyKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-idempotency-key", headerParam0)
		}

	}

	return req, nil
}

// NewGetPredictionApiV1PredictPredictionsPredictionIdGetRequest generates requests for GetPredictionApiV1PredictPredictionsPredictionIdGet
func NewGetPredictionApiV1PredictPredictionsPredictionIdGetRequest(server string, predictionId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "prediction_id", runtime.ParamLocationPath, predictionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/predict/predictions/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// EdgesForGameApiV1PredictGamesGameIdEdgesGetWithResponse request
	EdgesForGameApiV1PredictGamesGameIdEdgesGetWithResponse(ctx context.Context, gameId string, params *EdgesForGameApiV1PredictGamesGameIdEdgesGetParams, reqEditors ...RequestEditorFn) (*EdgesForGameApiV1PredictGamesGameIdEdgesGetResponse, error)

	// LatestPredictionsApiV1PredictGamesGameIdLatestGetWithResponse request
	LatestPredictionsApiV1PredictGamesGameIdLatestGetWithResponse(ctx context.Context, gameId string, params *LatestPredictionsApiV1PredictGamesGameIdLatestGetParams, reqEditors ...RequestEditorFn) (*LatestPredictionsApiV1PredictGamesGameIdLatestGetResponse, error)

	// GetHealthApiV1PredictHealthGetWithResponse request
	GetHealthApiV1PredictHealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthApiV1PredictHealthGetResponse, error)

	// ListModelsApiV1PredictModelsGetWithResponse request
	ListModelsApiV1PredictModelsGetWithResponse(ctx context.Context, params *ListModelsApiV1PredictModelsGetParams, reqEditors ...RequestEditorFn) (*ListModelsApiV1PredictModelsGetResponse, error)

	// RetrainModelApiV1PredictModelsRetrainPostWithBodyWithResponse request with any body
	RetrainModelApiV1PredictModelsRetrainPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RetrainModelApiV1PredictModelsRetrainPostResponse, error)

	RetrainModelApiV1PredictModelsRetrainPostWithResponse(ctx context.Context, body RetrainModelApiV1PredictModelsRetrainPostJSONRequestBody, reqEditors ...RequestEditorFn) (*RetrainModelApiV1PredictModelsRetrainPostResponse, error)

	// GetModelApiV1PredictModelsModelIdGetWithResponse request
	GetModelApiV1PredictModelsModelIdGetWithResponse(ctx context.Context, modelId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetModelApiV1PredictModelsModelIdGetResponse, error)

	// CreatePredictionsApiV1PredictPredictionsPostWithBodyWithResponse request with any body
	CreatePredictionsApiV1PredictPredictionsPostWithBodyWithResponse(ctx context.Context, params *CreatePredictionsApiV1PredictPredictionsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePredictionsApiV1PredictPredictionsPostResponse, error)

	CreatePredictionsApiV1PredictPredictionsPostWithResponse(ctx context.Context, params *CreatePredictionsApiV1PredictPredictionsPostParams, body CreatePredictionsApiV1PredictPredictionsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePredictionsApiV1PredictPredictionsPostResponse, error)

	// GetPredictionApiV1PredictPredictionsPredictionIdGetWithResponse request
	GetPredictionApiV1PredictPredictionsPredictionIdGetWithResponse(ctx context.Context, predictionId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetPredictionApiV1PredictPredictionsPredictionIdGetResponse, error)
}

type EdgesForGameApiV1PredictGamesGameIdEdgesGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeEdgesData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r EdgesForGameApiV1PredictGamesGameIdEdgesGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r EdgesForGameApiV1PredictGamesGameIdEdgesGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type LatestPredictionsApiV1PredictGamesGameIdLatestGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeLatestPredictionsData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r LatestPredictionsApiV1PredictGamesGameIdLatestGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LatestPredictionsApiV1PredictGamesGameIdLatestGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthApiV1PredictHealthGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeHealthData
}

// Status returns HTTPResponse.Status
func (r GetHealthApiV1PredictHealthGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthApiV1PredictHealthGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListModelsApiV1PredictModelsGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeListModelVersionData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r ListModelsApiV1PredictModelsGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListModelsApiV1PredictModelsGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RetrainModelApiV1PredictModelsRetrainPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *EnvelopeRetrainData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r RetrainModelApiV1PredictModelsRetrainPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RetrainModelApiV1PredictModelsRetrainPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetModelApiV1PredictModelsModelIdGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopeModelVersionDetailData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetModelApiV1PredictModelsModelIdGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetModelApiV1PredictModelsModelIdGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreatePredictionsApiV1PredictPredictionsPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *EnvelopePredictionGroupData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r CreatePredictionsApiV1PredictPredictionsPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePredictionsApiV1PredictPredictionsPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPredictionApiV1PredictPredictionsPredictionIdGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvelopePredictionDetailData
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetPredictionApiV1PredictPredictionsPredictionIdGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPredictionApiV1PredictPredictionsPredictionIdGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// EdgesForGameApiV1PredictGamesGameIdEdgesGetWithResponse request returning *EdgesForGameApiV1PredictGamesGameIdEdgesGetResponse
func (c *ClientWithResponses) EdgesForGameApiV1PredictGamesGameIdEdgesGetWithResponse(ctx context.Context, gameId string, params *EdgesForGameApiV1PredictGamesGameIdEdgesGetParams, reqEditors ...RequestEditorFn) (*EdgesForGameApiV1PredictGamesGameIdEdgesGetResponse, error) {
	rsp, err := c.EdgesForGameApiV1PredictGamesGameIdEdgesGet(ctx, gameId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEdgesForGameApiV1PredictGamesGameIdEdgesGetResponse(rsp)
}

// LatestPredictionsApiV1PredictGamesGameIdLatestGetWithResponse request returning *LatestPredictionsApiV1PredictGamesGameIdLatestGetResponse
func (c *ClientWithResponses) LatestPredictionsApiV1PredictGamesGameIdLatestGetWithResponse(ctx context.Context, gameId string, params *LatestPredictionsApiV1PredictGamesGameIdLatestGetParams, reqEditors ...RequestEditorFn) (*LatestPredictionsApiV1PredictGamesGameIdLatestGetResponse, error) {
	rsp, err := c.LatestPredictionsApiV1PredictGamesGameIdLatestGet(ctx, gameId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLatestPredictionsApiV1PredictGamesGameIdLatestGetResponse(rsp)
}

// GetHealthApiV1PredictHealthGetWithResponse request returning *GetHealthApiV1PredictHealthGetResponse
func (c *ClientWithResponses) GetHealthApiV1PredictHealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthApiV1PredictHealthGetResponse, error) {
	rsp, err := c.GetHealthApiV1PredictHealthGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthApiV1PredictHealthGetResponse(rsp)
}

// ListModelsApiV1PredictModelsGetWithResponse request returning *ListModelsApiV1PredictModelsGetResponse
func (c *ClientWithResponses) ListModelsApiV1PredictModelsGetWithResponse(ctx context.Context, params *ListModelsApiV1PredictModelsGetParams, reqEditors ...RequestEditorFn) (*ListModelsApiV1PredictModelsGetResponse, error) {
	rsp, err := c.ListModelsApiV1PredictModelsGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListModelsApiV1PredictModelsGetResponse(rsp)
}

// RetrainModelApiV1PredictModelsRetrainPostWithBodyWithResponse request with arbitrary body returning *RetrainModelApiV1PredictModelsRetrainPostResponse
func (c *ClientWithResponses) RetrainModelApiV1PredictModelsRetrainPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RetrainModelApiV1PredictModelsRetrainPostResponse, error) {
	rsp, err := c.RetrainModelApiV1PredictModelsRetrainPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRetrainModelApiV1PredictModelsRetrainPostResponse(rsp)
}

func (c *ClientWithResponses) RetrainModelApiV1PredictModelsRetrainPostWithResponse(ctx context.Context, body RetrainModelApiV1PredictModelsRetrainPostJSONRequestBody, reqEditors ...RequestEditorFn) (*RetrainModelApiV1PredictModelsRetrainPostResponse, error) {
	rsp, err := c.RetrainModelApiV1PredictModelsRetrainPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRetrainModelApiV1PredictModelsRetrainPostResponse(rsp)
}

// GetModelApiV1PredictModelsModelIdGetWithResponse request returning *GetModelApiV1PredictModelsModelIdGetResponse
func (c *ClientWithResponses) GetModelApiV1PredictModelsModelIdGetWithResponse(ctx context.Context, modelId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetModelApiV1PredictModelsModelIdGetResponse, error) {
	rsp, err := c.GetModelApiV1PredictModelsModelIdGet(ctx, modelId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetModelApiV1PredictModelsModelIdGetResponse(rsp)
}

// CreatePredictionsApiV1PredictPredictionsPostWithBodyWithResponse request with arbitrary body returning *CreatePredictionsApiV1PredictPredictionsPostResponse
func (c *ClientWithResponses) CreatePredictionsApiV1PredictPredictionsPostWithBodyWithResponse(ctx context.Context, params *CreatePredictionsApiV1PredictPredictionsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePredictionsApiV1PredictPredictionsPostResponse, error) {
	rsp, err := c.CreatePredictionsApiV1PredictPredictionsPostWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePredictionsApiV1PredictPredictionsPostResponse(rsp)
}

func (c *ClientWithResponses) CreatePredictionsApiV1PredictPredictionsPostWithResponse(ctx context.Context, params *CreatePredictionsApiV1PredictPredictionsPostParams, body CreatePredictionsApiV1PredictPredictionsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePredictionsApiV1PredictPredictionsPostResponse, error) {
	rsp, err := c.CreatePredictionsApiV1PredictPredictionsPost(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePredictionsApiV1PredictPredictionsPostResponse(rsp)
}

// GetPredictionApiV1PredictPredictionsPredictionIdGetWithResponse request returning *GetPredictionApiV1PredictPredictionsPredictionIdGetResponse
func (c *ClientWithResponses) GetPredictionApiV1PredictPredictionsPredictionIdGetWithResponse(ctx context.Context, predictionId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetPredictionApiV1PredictPredictionsPredictionIdGetResponse, error) {
	rsp, err := c.GetPredictionApiV1PredictPredictionsPredictionIdGet(ctx, predictionId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPredictionApiV1PredictPredictionsPredictionIdGetResponse(rsp)
}

// ParseEdgesForGameApiV1PredictGamesGameIdEdgesGetResponse parses an HTTP response from a EdgesForGameApiV1PredictGamesGameIdEdgesGetWithResponse call
func ParseEdgesForGameApiV1PredictGamesGameIdEdgesGetResponse(rsp *http.Response) (*EdgesForGameApiV1PredictGamesGameIdEdgesGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &EdgesForGameApiV1PredictGamesGameIdEdgesGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeEdgesData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseLatestPredictionsApiV1PredictGamesGameIdLatestGetResponse parses an HTTP response from a LatestPredictionsApiV1PredictGamesGameIdLatestGetWithResponse call
func ParseLatestPredictionsApiV1PredictGamesGameIdLatestGetResponse(rsp *http.Response) (*LatestPredictionsApiV1PredictGamesGameIdLatestGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LatestPredictionsApiV1PredictGamesGameIdLatestGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeLatestPredictionsData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetHealthApiV1PredictHealthGetResponse parses an HTTP response from a GetHealthApiV1PredictHealthGetWithResponse call
func ParseGetHealthApiV1PredictHealthGetResponse(rsp *http.Response) (*GetHealthApiV1PredictHealthGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthApiV1PredictHealthGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeHealthData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListModelsApiV1PredictModelsGetResponse parses an HTTP response from a ListModelsApiV1PredictModelsGetWithResponse call
func ParseListModelsApiV1PredictModelsGetResponse(rsp *http.Response) (*ListModelsApiV1PredictModelsGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListModelsApiV1PredictModelsGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeListModelVersionData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseRetrainModelApiV1PredictModelsRetrainPostResponse parses an HTTP response from a RetrainModelApiV1PredictModelsRetrainPostWithResponse call
func ParseRetrainModelApiV1PredictModelsRetrainPostResponse(rsp *http.Response) (*RetrainModelApiV1PredictModelsRetrainPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RetrainModelApiV1PredictModelsRetrainPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest EnvelopeRetrainData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetModelApiV1PredictModelsModelIdGetResponse parses an HTTP response from a GetModelApiV1PredictModelsModelIdGetWithResponse call
func ParseGetModelApiV1PredictModelsModelIdGetResponse(rsp *http.Response) (*GetModelApiV1PredictModelsModelIdGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetModelApiV1PredictModelsModelIdGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopeModelVersionDetailData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseCreatePredictionsApiV1PredictPredictionsPostResponse parses an HTTP response from a CreatePredictionsApiV1PredictPredictionsPostWithResponse call
func ParseCreatePredictionsApiV1PredictPredictionsPostResponse(rsp *http.Response) (*CreatePredictionsApiV1PredictPredictionsPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePredictionsApiV1PredictPredictionsPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest EnvelopePredictionGroupData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetPredictionApiV1PredictPredictionsPredictionIdGetResponse parses an HTTP response from a GetPredictionApiV1PredictPredictionsPredictionIdGetWithResponse call
func ParseGetPredictionApiV1PredictPredictionsPredictionIdGetResponse(rsp *http.Response) (*GetPredictionApiV1PredictPredictionsPredictionIdGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPredictionApiV1PredictPredictionsPredictionIdGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvelopePredictionDetailData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
