// Package linesservice provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package linesservice

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthResponseDependenciesStatus.
const (
	HealthResponseDependenciesStatusHealthy   HealthResponseDependenciesStatus = "healthy"
	HealthResponseDependenciesStatusUnhealthy HealthResponseDependenciesStatus = "unhealthy"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDegraded  HealthResponseStatus = "degraded"
	HealthResponseStatusHealthy   HealthResponseStatus = "healthy"
	HealthResponseStatusUnhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for LineSnapshotMarketType.
const (
	FUTURE     LineSnapshotMarketType = "FUTURE"
	GAMEPROP   LineSnapshotMarketType = "GAME_PROP"
	LIVE       LineSnapshotMarketType = "LIVE"
	MONEYLINE  LineSnapshotMarketType = "MONEYLINE"
	PLAYERPROP LineSnapshotMarketType = "PLAYER_PROP"
	SPREAD     LineSnapshotMarketType = "SPREAD"
	TEAMPROP   LineSnapshotMarketType = "TEAM_PROP"
	TOTAL      LineSnapshotMarketType = "TOTAL"
)

// Defines values for LineSnapshotSide.
const (
	AWAY  LineSnapshotSide = "AWAY"
	HOME  LineSnapshotSide = "HOME"
	NO    LineSnapshotSide = "NO"
	OVER  LineSnapshotSide = "OVER"
	UNDER LineSnapshotSide = "UNDER"
	YES   LineSnapshotSide = "YES"
)

// BestLine defines model for BestLine.
type BestLine struct {
	BestOddsAmerican   *int                `json:"best_odds_american,omitempty"`
	BestOddsDecimal    *float32            `json:"best_odds_decimal,omitempty"`
	ImpliedProbability *float32            `json:"implied_probability,omitempty"`
	LineId             *openapi_types.UUID `json:"line_id,omitempty"`
	LineValue          *float32            `json:"line_value"`
	MarketType         *string             `json:"market_type,omitempty"`
	Selection          *string             `json:"selection,omitempty"`
	Side               *string             `json:"side,omitempty"`
	SportsbookId       *openapi_types.UUID `json:"sportsbook_id,omitempty"`
	SportsbookKey      *string             `json:"sportsbook_key,omitempty"`
	SportsbookName     *string             `json:"sportsbook_name,omitempty"`
	Timestamp          *time.Time          `json:"timestamp,omitempty"`
}

// BestLineListResponse defines model for BestLineListResponse.
type BestLineListResponse struct {
	Data []BestLine `json:"data"`
	Meta Meta       `json:"meta"`
}

// ClosingLine defines model for ClosingLine.
type ClosingLine struct {
	CapturedAt    *time.Time          `json:"captured_at,omitempty"`
	GameId        *string             `json:"game_id,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	LineValue     *float32            `json:"line_value"`
	MarketType    *string             `json:"market_type,omitempty"`
	OddsAmerican  *int                `json:"odds_american,omitempty"`
	OddsDecimal   *float32            `json:"odds_decimal,omitempty"`
	Selection     *string             `json:"selection,omitempty"`
	SportsbookId  *openapi_types.UUID `json:"sportsbook_id,omitempty"`
	SportsbookKey *string             `json:"sportsbook_key,omitempty"`
}

// ClosingLineListResponse defines model for ClosingLineListResponse.
type ClosingLineListResponse struct {
	Data []ClosingLine `json:"data"`
	Meta Meta          `json:"meta"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    string                  `json:"code"`
		Details *map[string]interface{} `json:"details,omitempty"`
		Message string                  `json:"message"`
	} `json:"error"`
	Meta Meta `json:"meta"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Dependencies *map[string]struct {
		LatencyMs *float32                          `json:"latency_ms,omitempty"`
		Status    *HealthResponseDependenciesStatus `json:"status,omitempty"`
	} `json:"dependencies,omitempty"`
	Service       string               `json:"service"`
	Status        HealthResponseStatus `json:"status"`
	UptimeSeconds *float32             `json:"uptime_seconds,omitempty"`
	Version       string               `json:"version"`
}

// HealthResponseDependenciesStatus defines model for HealthResponse.Dependencies.Status.
type HealthResponseDependenciesStatus string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// IngestionTriggerResponse defines model for IngestionTriggerResponse.
type IngestionTriggerResponse struct {
	Data struct {
		League  *string `json:"league,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"data"`
	Meta Meta `json:"meta"`
}

// LineMovement defines model for LineMovement.
type LineMovement struct {
	ClosingLine       *float32                `json:"closing_line"`
	ClosingOdds       *int                    `json:"closing_odds"`
	CurrentLine       *float32                `json:"current_line"`
	CurrentOdds       *int                    `json:"current_odds,omitempty"`
	GameId            *string                 `json:"game_id,omitempty"`
	IsReverseMovement *bool                   `json:"is_reverse_movement,omitempty"`
	LineSnapshots     *[]LineMovementSnapshot `json:"line_snapshots,omitempty"`
	MarketType        *string                 `json:"market_type,omitempty"`
	OpeningLine       *float32                `json:"opening_line"`
	OpeningOdds       *int                    `json:"opening_odds"`
	Selection         *string                 `json:"selection,omitempty"`
	SportsbookId      *openapi_types.UUID     `json:"sportsbook_id,omitempty"`
	SportsbookKey     *string                 `json:"sportsbook_key,omitempty"`
	TotalMovement     *float32                `json:"total_movement"`
}

// LineMovementListResponse defines model for LineMovementListResponse.
type LineMovementListResponse struct {
	Data []LineMovement `json:"data"`
	Meta Meta           `json:"meta"`
}

// LineMovementSnapshot defines model for LineMovementSnapshot.
type LineMovementSnapshot struct {
	IsOpening    *bool      `json:"is_opening,omitempty"`
	LineValue    *float32   `json:"line_value,omitempty"`
	OddsAmerican *int       `json:"odds_american,omitempty"`
	Timestamp    *time.Time `json:"timestamp,omitempty"`
}

// LineSnapshot defines model for LineSnapshot.
type LineSnapshot struct {
	GameId             string                 `json:"game_id"`
	Id                 openapi_types.UUID     `json:"id"`
	ImpliedProbability float32                `json:"implied_probability"`
	IsClosing          *bool                  `json:"is_closing,omitempty"`
	IsOpening          *bool                  `json:"is_opening,omitempty"`
	LineValue          *float32               `json:"line_value"`
	MarketType         LineSnapshotMarketType `json:"market_type"`
	OddsAmerican       int                    `json:"odds_american"`
	OddsDecimal        float32                `json:"odds_decimal"`
	Selection          string                 `json:"selection"`
	Side               *LineSnapshotSide      `json:"side,omitempty"`
	SportsbookId       openapi_types.UUID     `json:"sportsbook_id"`
	SportsbookKey      string                 `json:"sportsbook_key"`
	Timestamp          time.Time              `json:"timestamp"`
}

// LineSnapshotMarketType defines model for LineSnapshot.MarketType.
type LineSnapshotMarketType string

// LineSnapshotSide defines model for LineSnapshot.Side.
type LineSnapshotSide string

// LineSnapshotListResponse defines model for LineSnapshotListResponse.
type LineSnapshotListResponse struct {
	Data []LineSnapshot `json:"data"`
	Meta Meta           `json:"meta"`
}

// LineSnapshotResponse defines model for LineSnapshotResponse.
type LineSnapshotResponse struct {
	Data LineSnapshot `json:"data"`
	Meta Meta         `json:"meta"`
}

// Meta defines model for Meta.
type Meta struct {
	Pagination *PaginationMeta    `json:"pagination,omitempty"`
	RequestId  openapi_types.UUID `json:"request_id"`
	Timestamp  time.Time          `json:"timestamp"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	HasMore    *bool   `json:"has_more,omitempty"`
	Limit      *int    `json:"limit,omitempty"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Sportsbook defines model for Sportsbook.
type Sportsbook struct {
	Id       openapi_types.UUID `json:"id"`
	IsActive bool               `json:"is_active"`
	IsSharp  bool               `json:"is_sharp"`
	Key      string             `json:"key"`
	Name     string             `json:"name"`
}

// SportsbookListResponse defines model for SportsbookListResponse.
type SportsbookListResponse struct {
	Data []Sportsbook `json:"data"`
	Meta Meta         `json:"meta"`
}

// Cursor defines model for Cursor.
type Cursor = string

// GameId defines model for GameId.
type GameId = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// GetCurrentLinesParams defines parameters for GetCurrentLines.
type GetCurrentLinesParams struct {
	// League Filter by league (comma-separated)
	League *string `form:"league,omitempty" json:"league,omitempty"`

	// GameId Filter by game UUID (comma-separated)
	GameId *string `form:"game_id,omitempty" json:"game_id,omitempty"`

	// Sportsbook Filter by sportsbook key (comma-separated)
	Sportsbook *string `form:"sportsbook,omitempty" json:"sportsbook,omitempty"`

	// MarketType Filter by market type (comma-separated)
	MarketType *string `form:"market_type,omitempty" json:"market_type,omitempty"`

	// Date Filter by game date (ISO 8601)
	Date *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`

	// Limit Maximum number of items to return per page.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response's meta.next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetGameLinesParams defines parameters for GetGameLines.
type GetGameLinesParams struct {
	// MarketType Filter by market type (e.g. SPREAD, TOTAL, MONEYLINE).
	MarketType *string `form:"market_type,omitempty" json:"market_type,omitempty"`

	// Sportsbook Filter by sportsbook key (e.g. draftkings, pinnacle).
	Sportsbook *string `form:"sportsbook,omitempty" json:"sportsbook,omitempty"`

	// Side Filter by selection side (e.g. home, away, over, under).
	Side *string `form:"side,omitempty" json:"side,omitempty"`

	// Limit Maximum number of items to return per page.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response's meta.next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetGameBestLinesParams defines parameters for GetGameBestLines.
type GetGameBestLinesParams struct {
	// MarketType Filter by market type (e.g. SPREAD, TOTAL, MONEYLINE).
	MarketType *string `form:"market_type,omitempty" json:"market_type,omitempty"`

	// Selection Filter by selection (e.g. home, away, over, under).
	Selection *string `form:"selection,omitempty" json:"selection,omitempty"`
}

// GetGameClosingLinesParams defines parameters for GetGameClosingLines.
type GetGameClosingLinesParams struct {
	// Sportsbook Filter by sportsbook key (e.g. draftkings, pinnacle).
	Sportsbook *string `form:"sportsbook,omitempty" json:"sportsbook,omitempty"`

	// MarketType Filter by market type (e.g. SPREAD, TOTAL, MONEYLINE).
	MarketType *string `form:"market_type,omitempty" json:"market_type,omitempty"`
}

// GetGameLineMovementParams defines parameters for GetGameLineMovement.
type GetGameLineMovementParams struct {
	// Sportsbook Restrict movement history to a single sportsbook key.
	Sportsbook *string `form:"sportsbook,omitempty" json:"sportsbook,omitempty"`

	// MarketType Market type to chart (e.g. SPREAD, TOTAL, MONEYLINE).
	MarketType *string `form:"market_type,omitempty" json:"market_type,omitempty"`

	// Selection Restrict movement history to a single selection (e.g. home, over).
	Selection *string `form:"selection,omitempty" json:"selection,omitempty"`
}

// TriggerIngestionJSONBody defines parameters for TriggerIngestion.
type TriggerIngestionJSONBody struct {
	// League League to ingest (default all active)
	League *string `json:"league,omitempty"`
}

// GetSportsbooksParams defines parameters for GetSportsbooks.
type GetSportsbooksParams struct {
	// IsSharp Filter to sharp (market-making) sportsbooks such as Pinnacle or Circa.
	IsSharp *bool `form:"is_sharp,omitempty" json:"is_sharp,omitempty"`

	// IsActive Filter to sportsbooks that are actively ingested.
	IsActive *bool `form:"is_active,omitempty" json:"is_active,omitempty"`
}

// TriggerIngestionJSONRequestBody defines body for TriggerIngestion for application/json ContentType.
type TriggerIngestionJSONRequestBody TriggerIngestionJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetCurrentLines request
	GetCurrentLines(ctx context.Context, params *GetCurrentLinesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGameLines request
	GetGameLines(ctx context.Context, gameId GameId, params *GetGameLinesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGameBestLines request
	GetGameBestLines(ctx context.Context, gameId GameId, params *GetGameBestLinesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGameClosingLines request
	GetGameClosingLines(ctx context.Context, gameId GameId, params *GetGameClosingLinesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGameLineMovement request
	GetGameLineMovement(ctx context.Context, gameId GameId, params *GetGameLineMovementParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TriggerIngestionWithBody request with any body
	TriggerIngestionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TriggerIngestion(ctx context.Context, body TriggerIngestionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetLineSnapshot request
	GetLineSnapshot(ctx context.Context, lineId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSportsbooks request
	GetSportsbooks(ctx context.Context, params *GetSportsbooksParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetCurrentLines(ctx context.Context, params *GetCurrentLinesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCurrentLinesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGameLines(ctx context.Context, gameId GameId, params *GetGameLinesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGameLinesRequest(c.Server, gameId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGameBestLines(ctx context.Context, gameId GameId, params *GetGameBestLinesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGameBestLinesRequest(c.Server, gameId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGameClosingLines(ctx context.Context, gameId GameId, params *GetGameClosingLinesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGameClosingLinesRequest(c.Server, gameId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGameLineMovement(ctx context.Context, gameId GameId, params *GetGameLineMovementParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGameLineMovementRequest(c.Server, gameId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TriggerIngestionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTriggerIngestionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TriggerIngestion(ctx context.Context, body TriggerIngestionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTriggerIngestionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetLineSnapshot(ctx context.Context, lineId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLineSnapshotRequest(c.Server, lineId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSportsbooks(ctx context.Context, params *GetSportsbooksParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSportsbooksRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCurrentLinesRequest generates requests for GetCurrentLines
func NewGetCurrentLinesRequest(server string, params *GetCurrentLinesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/lines/current")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.League != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "league", runtime.ParamLocationQuery, *params.League); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.GameId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "game_id", runtime.ParamLocationQuery, *params.GameId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Sportsbook != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sportsbook", runtime.ParamLocationQuery, *params.Sportsbook); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MarketType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "market_type", runtime.ParamLocationQuery, *params.MarketType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Date != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "date", runtime.ParamLocationQuery, *params.Date); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetGameLinesRequest generates requests for GetGameLines
func NewGetGameLinesRequest(server string, gameId GameId, params *GetGameLinesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "game_id", runtime.ParamLocationPath, gameId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/lines/game/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.MarketType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "market_type", runtime.ParamLocationQuery, *params.MarketType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Sportsbook != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sportsbook", runtime.ParamLocationQuery, *params.Sportsbook); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Side != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "side", runtime.ParamLocationQuery, *params.Side); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetGameBestLinesRequest generates requests for GetGameBestLines
func NewGetGameBestLinesRequest(server string, gameId GameId, params *GetGameBestLinesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "game_id", runtime.ParamLocationPath, gameId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/lines/game/%s/best", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.MarketType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "market_type", runtime.ParamLocationQuery, *params.MarketType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Selection != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "selection", runtime.ParamLocationQuery, *params.Selection); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetGameClosingLinesRequest generates requests for GetGameClosingLines
func NewGetGameClosingLinesRequest(server string, gameId GameId, params *GetGameClosingLinesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "game_id", runtime.ParamLocationPath, gameId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/lines/game/%s/closing", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Sportsbook != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sportsbook", runtime.ParamLocationQuery, *params.Sportsbook); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MarketType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "market_type", runtime.ParamLocationQuery, *params.MarketType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetGameLineMovementRequest generates requests for GetGameLineMovement
func NewGetGameLineMovementRequest(server string, gameId GameId, params *GetGameLineMovementParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "game_id", runtime.ParamLocationPath, gameId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/lines/game/%s/movement", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Sportsbook != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sportsbook", runtime.ParamLocationQuery, *params.Sportsbook); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MarketType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "market_type", runtime.ParamLocationQuery, *params.MarketType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Selection != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "selection", runtime.ParamLocationQuery, *params.Selection); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/lines/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTriggerIngestionRequest calls the generic TriggerIngestion builder with application/json body
func NewTriggerIngestionRequest(server string, body TriggerIngestionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTriggerIngestionRequestWithBody(server, "application/json", bodyReader)
}

// NewTriggerIngestionRequestWithBody generates requests for TriggerIngestion with any type of body
func NewTriggerIngestionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/lines/ingestion/trigger")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetLineSnapshotRequest generates requests for GetLineSnapshot
func NewGetLineSnapshotRequest(server string, lineId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "line_id", runtime.ParamLocationPath, lineId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/lines/snapshots/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSportsbooksRequest generates requests for GetSportsbooks
func NewGetSportsbooksRequest(server string, params *GetSportsbooksParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/lines/sportsbooks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.IsSharp != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "is_sharp", runtime.ParamLocationQuery, *params.IsSharp); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.IsActive != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "is_active", runtime.ParamLocationQuery, *params.IsActive); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetCurrentLinesWithResponse request
	GetCurrentLinesWithResponse(ctx context.Context, params *GetCurrentLinesParams, reqEditors ...RequestEditorFn) (*GetCurrentLinesResponse, error)

	// GetGameLinesWithResponse request
	GetGameLinesWithResponse(ctx context.Context, gameId GameId, params *GetGameLinesParams, reqEditors ...RequestEditorFn) (*GetGameLinesResponse, error)

	// GetGameBestLinesWithResponse request
	GetGameBestLinesWithResponse(ctx context.Context, gameId GameId, params *GetGameBestLinesParams, reqEditors ...RequestEditorFn) (*GetGameBestLinesResponse, error)

	// GetGameClosingLinesWithResponse request
	GetGameClosingLinesWithResponse(ctx context.Context, gameId GameId, params *GetGameClosingLinesParams, reqEditors ...RequestEditorFn) (*GetGameClosingLinesResponse, error)

	// GetGameLineMovementWithResponse request
	GetGameLineMovementWithResponse(ctx context.Context, gameId GameId, params *GetGameLineMovementParams, reqEditors ...RequestEditorFn) (*GetGameLineMovementResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// TriggerIngestionWithBodyWithResponse request with any body
	TriggerIngestionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TriggerIngestionResponse, error)

	TriggerIngestionWithResponse(ctx context.Context, body TriggerIngestionJSONRequestBody, reqEditors ...RequestEditorFn) (*TriggerIngestionResponse, error)

	// GetLineSnapshotWithResponse request
	GetLineSnapshotWithResponse(ctx context.Context, lineId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetLineSnapshotResponse, error)

	// GetSportsbooksWithResponse request
	GetSportsbooksWithResponse(ctx context.Context, params *GetSportsbooksParams, reqEditors ...RequestEditorFn) (*GetSportsbooksResponse, error)
}

type GetCurrentLinesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LineSnapshotListResponse
}

// Status returns HTTPResponse.Status
func (r GetCurrentLinesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCurrentLinesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetGameLinesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LineSnapshotListResponse
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetGameLinesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGameLinesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetGameBestLinesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BestLineListResponse
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetGameBestLinesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGameBestLinesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetGameClosingLinesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ClosingLineListResponse
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetGameClosingLinesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGameClosingLinesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetGameLineMovementResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LineMovementListResponse
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetGameLineMovementResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGameLineMovementResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
	JSON503      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TriggerIngestionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *IngestionTriggerResponse
}

// Status returns HTTPResponse.Status
func (r TriggerIngestionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TriggerIngestionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetLineSnapshotResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LineSnapshotResponse
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetLineSnapshotResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetLineSnapshotResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSportsbooksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SportsbookListResponse
}

// Status returns HTTPResponse.Status
func (r GetSportsbooksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSportsbooksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetCurrentLinesWithResponse request returning *GetCurrentLinesResponse
func (c *ClientWithResponses) GetCurrentLinesWithResponse(ctx context.Context, params *GetCurrentLinesParams, reqEditors ...RequestEditorFn) (*GetCurrentLinesResponse, error) {
	rsp, err := c.GetCurrentLines(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCurrentLinesResponse(rsp)
}

// GetGameLinesWithResponse request returning *GetGameLinesResponse
func (c *ClientWithResponses) GetGameLinesWithResponse(ctx context.Context, gameId GameId, params *GetGameLinesParams, reqEditors ...RequestEditorFn) (*GetGameLinesResponse, error) {
	rsp, err := c.GetGameLines(ctx, gameId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGameLinesResponse(rsp)
}

// GetGameBestLinesWithResponse request returning *GetGameBestLinesResponse
func (c *ClientWithResponses) GetGameBestLinesWithResponse(ctx context.Context, gameId GameId, params *GetGameBestLinesParams, reqEditors ...RequestEditorFn) (*GetGameBestLinesResponse, error) {
	rsp, err := c.GetGameBestLines(ctx, gameId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGameBestLinesResponse(rsp)
}

// GetGameClosingLinesWithResponse request returning *GetGameClosingLinesResponse
func (c *ClientWithResponses) GetGameClosingLinesWithResponse(ctx context.Context, gameId GameId, params *GetGameClosingLinesParams, reqEditors ...RequestEditorFn) (*GetGameClosingLinesResponse, error) {
	rsp, err := c.GetGameClosingLines(ctx, gameId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGameClosingLinesResponse(rsp)
}

// GetGameLineMovementWithResponse request returning *GetGameLineMovementResponse
func (c *ClientWithResponses) GetGameLineMovementWithResponse(ctx context.Context, gameId GameId, params *GetGameLineMovementParams, reqEditors ...RequestEditorFn) (*GetGameLineMovementResponse, error) {
	rsp, err := c.GetGameLineMovement(ctx, gameId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGameLineMovementResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// TriggerIngestionWithBodyWithResponse request with arbitrary body returning *TriggerIngestionResponse
func (c *ClientWithResponses) TriggerIngestionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TriggerIngestionResponse, error) {
	rsp, err := c.TriggerIngestionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTriggerIngestionResponse(rsp)
}

func (c *ClientWithResponses) TriggerIngestionWithResponse(ctx context.Context, body TriggerIngestionJSONRequestBody, reqEditors ...RequestEditorFn) (*TriggerIngestionResponse, error) {
	rsp, err := c.TriggerIngestion(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTriggerIngestionResponse(rsp)
}

// GetLineSnapshotWithResponse request returning *GetLineSnapshotResponse
func (c *ClientWithResponses) GetLineSnapshotWithResponse(ctx context.Context, lineId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetLineSnapshotResponse, error) {
	rsp, err := c.GetLineSnapshot(ctx, lineId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetLineSnapshotResponse(rsp)
}

// GetSportsbooksWithResponse request returning *GetSportsbooksResponse
func (c *ClientWithResponses) GetSportsbooksWithResponse(ctx context.Context, params *GetSportsbooksParams, reqEditors ...RequestEditorFn) (*GetSportsbooksResponse, error) {
	rsp, err := c.GetSportsbooks(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSportsbooksResponse(rsp)
}

// ParseGetCurrentLinesResponse parses an HTTP response from a GetCurrentLinesWithResponse call
func ParseGetCurrentLinesResponse(rsp *http.Response) (*GetCurrentLinesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCurrentLinesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LineSnapshotListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetGameLinesResponse parses an HTTP response from a GetGameLinesWithResponse call
func ParseGetGameLinesResponse(rsp *http.Response) (*GetGameLinesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGameLinesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LineSnapshotListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetGameBestLinesResponse parses an HTTP response from a GetGameBestLinesWithResponse call
func ParseGetGameBestLinesResponse(rsp *http.Response) (*GetGameBestLinesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGameBestLinesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BestLineListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetGameClosingLinesResponse parses an HTTP response from a GetGameClosingLinesWithResponse call
func ParseGetGameClosingLinesResponse(rsp *http.Response) (*GetGameClosingLinesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGameClosingLinesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ClosingLineListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetGameLineMovementResponse parses an HTTP response from a GetGameLineMovementWithResponse call
func ParseGetGameLineMovementResponse(rsp *http.Response) (*GetGameLineMovementResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGameLineMovementResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LineMovementListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseTriggerIngestionResponse parses an HTTP response from a TriggerIngestionWithResponse call
func ParseTriggerIngestionResponse(rsp *http.Response) (*TriggerIngestionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TriggerIngestionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest IngestionTriggerResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	}

	return response, nil
}

// ParseGetLineSnapshotResponse parses an HTTP response from a GetLineSnapshotWithResponse call
func ParseGetLineSnapshotResponse(rsp *http.Response) (*GetLineSnapshotResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetLineSnapshotResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LineSnapshotResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetSportsbooksResponse parses an HTTP response from a GetSportsbooksWithResponse call
func ParseGetSportsbooksResponse(rsp *http.Response) (*GetSportsbooksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSportsbooksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SportsbookListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
